### ISSUE TITLE
Conversion 'py2rpy' not defined for objects of type '<class 'str'>'

### ISSUE THREAD

**Issue by parthsarin** [rpy2/rpy2#956] opened 2022-11-07 21:18 UTC
**Describe the issue or bug**

The latest version of `rpy2` (version 3.5.5) seems to have a bug where cell magic in Google Colab notebooks is broken. Suggestions online are generally to [downgrade the package version](https://stackoverflow.com/questions/74283327/conversion-py2rpy-not-defined-for-objects-of-type-class-str). It looks like a string is being passed into `rpy2.robjects.conversion._py2rpy` which is throwing a `NotImplementedError`.

**To Reproduce**

[Here's a Google Colab notebook](https://colab.research.google.com/drive/1IcbwDWui12vz8GU1P3GcstgyTsNqej2p) with a simple example that creates this error. My original example was more complicated and looked more like this:

```
%load_ext rpy2.ipython
f = open('filename.csv').read()
```

and then the cell causing the error:

```
%%R -i f
df <- read.csv(text=f)
head(df,)
```

But it seems that there are simpler examples that cause this bug (see the notebook, where the error arises from adding two numbers together).

**Expected behavior**
The code should not raise an error.

**Error**
```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-2-847b2656f171> in <module>
----> 1 get_ipython().run_cell_magic('R', '', 'x <- 10\nx + 10\n')

8 frames
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2357             with self.builtin_trap:
   2358                 args = (magic_arg_s, cell)
-> 2359                 result = fn(*args, **kwargs)
   2360             return result
   2361 

<decorator-gen-122> in R(self, line, cell, local_ns)

/usr/local/lib/python3.7/dist-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

/usr/local/lib/python3.7/dist-packages/rpy2/ipython/rmagic.py in R(self, line, cell, local_ns)
    833             cell_display = CELL_DISPLAY_DEFAULT
    834 
--> 835         tmpd = self.setup_graphics(args)
    836 
    837         text_output = ''

/usr/local/lib/python3.7/dist-packages/rpy2/ipython/rmagic.py in setup_graphics(self, args)
    540                 # Note: that %% is to pass into R for interpolation there
    541                 grdevices.png("%s/Rplots%%03d.png" % tmpd_fix_slashes,
--> 542                               **argdict)
    543             elif self.device == 'svg':
    544                 self.cairo.CairoSVG("%s/Rplot.svg" % tmpd_fix_slashes,

/usr/local/lib/python3.7/dist-packages/rpy2/robjects/functions.py in __call__(self, *args, **kwargs)
    202                 kwargs[r_k] = v
    203         return (super(SignatureTranslatedFunction, self)
--> 204                 .__call__(*args, **kwargs))
    205 
    206 

/usr/local/lib/python3.7/dist-packages/rpy2/robjects/functions.py in __call__(self, *args, **kwargs)
    116     def __call__(self, *args, **kwargs):
    117         cv = conversion.get_conversion()
--> 118         new_args = [cv.py2rpy(a) for a in args]
    119         new_kwargs = {}
    120         for k, v in kwargs.items():

/usr/local/lib/python3.7/dist-packages/rpy2/robjects/functions.py in <listcomp>(.0)
    116     def __call__(self, *args, **kwargs):
    117         cv = conversion.get_conversion()
--> 118         new_args = [cv.py2rpy(a) for a in args]
    119         new_kwargs = {}
    120         for k, v in kwargs.items():

/usr/lib/python3.7/functools.py in wrapper(*args, **kw)
    838                             '1 positional argument')
    839 
--> 840         return dispatch(args[0].__class__)(*args, **kw)
    841 
    842     funcname = getattr(func, '__name__', 'singledispatch function')

/usr/local/lib/python3.7/dist-packages/rpy2/robjects/conversion.py in _py2rpy(obj)
    240     raise NotImplementedError(
    241         "Conversion 'py2rpy' not defined for objects of type '%s'" %
--> 242         str(type(obj))
    243     )
    244 

NotImplementedError: Conversion 'py2rpy' not defined for objects of type '<class 'str'>'
```

**Additional context**
```
rpy2 version:
3.5.5
Python version:
3.7.15 (default, Oct 12 2022, 19:14:55) 
[GCC 7.5.0]
Looking for R's HOME:
    Environment variable R_HOME: None
    Calling `R RHOME`: /usr/lib/R
    Environment variable R_LIBS_USER: None
R's additions to LD_LIBRARY_PATH:
/usr/local/nvidia/lib:/usr/local/nvidia/lib64
R version:
    In the PATH: R version 4.2.1 (2022-06-23) -- "Funny-Looking Kid"
    Loading R library from rpy2: OK
Additional directories to load R packages from:
None
C extension compilation:
  include:
  ['/usr/share/R/include']
  libraries:
  ['R', 'pcre2-8', 'lzma', 'bz2', 'z', 'rt', 'dl', 'm', 'icuuc', 'icui18n']
  library_dirs:
  ['/usr/lib/R/lib']
  extra_compile_args:
  []
  extra_link_args:
  ['-Wl,--export-dynamic', '-fopenmp', '-Wl,-Bsymbolic-functions', '-Wl,-z,relro']
```

**Comment by lgautier** [comment] 2022-11-08 04:42
Duplicate of https://github.com/googlecolab/colabtools/issues/3206

**Closed by lgautier** 2022-11-08 04:42 UTC
Labels: bug
