### ISSUE TITLE
Regression: LD Warning Related to libRblas.so and libR.so

### ISSUE THREAD

**Issue by steadmaj** [rpy2/rpy2#1043] opened 2023-06-26 21:06 UTC
**Describe the issue or bug**

When running pip3 install rpy2==3.5.13, the warning below is generated. The warning does not occur if rpy2 3.5.12 is used instead.       

/usr/bin/ld: warning: libRblas.so, needed by /opt/R-4.2.3.1687788884/lib64/R/lib/libR.so, not found (try using -rpath or -rpath-link)
      /opt/R-4.2.3.1687788884/lib64/R/lib/libR.so: undefined reference to `drot_'
      /opt/R-4.2.3.1687788884/lib64/R/lib/libR.so: undefined reference to `drotg_'
      /opt/R-4.2.3.1687788884/lib64/R/lib/libR.so: undefined reference to `dswap_'
      /opt/R-4.2.3.1687788884/lib64/R/lib/libR.so: undefined reference to `dgemm_'
      /opt/R-4.2.3.1687788884/lib64/R/lib/libR.so: undefined reference to `dnrm2_'
      /opt/R-4.2.3.1687788884/lib64/R/lib/libR.so: undefined reference to `dscal_'
      /opt/R-4.2.3.1687788884/lib64/R/lib/libR.so: undefined reference to `zgemm_'
      /opt/R-4.2.3.1687788884/lib64/R/lib/libR.so: undefined reference to `dtrsm_'
      /opt/R-4.2.3.1687788884/lib64/R/lib/libR.so: undefined reference to `daxpy_'
      /opt/R-4.2.3.1687788884/lib64/R/lib/libR.so: undefined reference to `dcopy_'
      /opt/R-4.2.3.1687788884/lib64/R/lib/libR.so: undefined reference to `dsyrk_'
      /opt/R-4.2.3.1687788884/lib64/R/lib/libR.so: undefined reference to `dasum_'
      /opt/R-4.2.3.1687788884/lib64/R/lib/libR.so: undefined reference to `ddot_'
      /opt/R-4.2.3.1687788884/lib64/R/lib/libR.so: undefined reference to `dgemv_'

**To Reproduce**

Using R 4.2.3 in PATH, Python 3.9.16, and PIP 23.1.2, execute pip3 install rpy2==3.5.13

**Expected behavior**

Version 3.5.13 installs without warning

**Error**

In description

**Additional context**

rpy2.situation is not available

**Comment by NGRhodes** [comment] 2023-06-29 12:50
This caught me out today creating a new environment.
Pinned to 3.5.12 for now.

**Comment by lgautier** [comment] 2023-07-04 02:41
Do you perform anything specific to help the linker find R's shared library?

Otherwise 3.5.13 is:
- fixing a bug with `python -m rpy2.situation LD_LIBRARY_PATH`: https://github.com/rpy2/rpy2/commit/659d0bbcc601a3f560ac4000fe7a3ba9cae8caac
- Fetching more completely how R itself is setting environment variables: https://github.com/rpy2/rpy2/commit/109c1c1719dedb143c1c7235b9d469e37bf0d4f5

May one of the two is at the root of this.

How is your R installed?

**Comment by steadmaj** [comment] 2023-07-14 14:33
Thanks for getting back to me. No, we do nothing specific or special related to the linker. The installation of R as well as Rpy2 is part of an automated process that is repeated several times daily. The process has been used for a few years. I'm working around the issue now by pinning the version to 3.5.12 (rpy2==3.5.12), which is not optimal as updates will be missed.

R is configured with the command './configure --prefix=/opt/R --enable-memory-profiling --enable-R-shlib --with-blas --with-lapack --with-readline=no --with-x=no --enable-BLAS-shlib' and the resulting R build is added to $PATH so it is found by pip.

**Comment by lgautier** [comment] 2023-07-22 18:08
May be related to issue #1045.

**Comment by lgautier** [comment] 2023-07-22 18:18
This could be an issue with a Python python packaging module (or an issue with the way I am using one of them). 3.5.13 no longer uses `distutils` since it is deprecated: https://github.com/rpy2/rpy2/blob/master/NEWS#L37

**Comment by lgautier** [comment] 2023-07-22 18:24
Can you try if updating `setuptools` fixes the issue?

**Comment by pur80a** [comment] 2023-07-28 15:36
```
$ pip3 freeze --all | grep setuptools
setuptools==68.0.0
setuptools-scm==7.1.0
```
This is the newest version of setuptools and I still get the same output (as in #1045).

**Comment by lgautier** [comment] 2023-07-29 13:29
I can't reproduce at the moment. My current hypothesis is that `setuptools`'s backcompatibility module with `distutils` does work as intended, or I misunderstand how it works.  This is the change in PR #1041.

Can someone with the issue try the followin?

1. `git clone` the `rpy2` repos
2. revert the change
```sh
git revert f2dd10dff36f3cbb128e3dddbbc2607d60fa61d2
```
3. install with 
```sh
pip install .
```

**Comment by steadmaj** [comment] 2023-07-31 14:58
The commit hash you provided did not work. Using git log, I found the hash value of what appears to be the commit just prior to the 3.5.13 (tag: RELEASE_3_5_13) release. Thank you for looking into this.

[user@test rpy2]$ pip3 list | grep setuptools
setuptools                   68.0.0

[user@test rpy2]$ git log
...
commit ea14dc344da3028c15119aea943c53919e2deb21
Author: Laurent Gautier <lgautier@gmail.com>
Date:   Mon Jun 19 19:41:42 2023 -0400

    Remove dependency on distutils. (#1041)
...

[user@test rpy2]$ git revert ea14dc344da3028c15119aea943c53919e2deb21
Auto-merging NEWS

[user@test rpy2]$ pip3 install .
Processing /opt/rpy2
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cffi>=1.10.0 in /opt/Python-3.9.16.1690578198/lib/python3.9/site-packages (from rpy2==3.5.14) (1.15.1)
Requirement already satisfied: jinja2 in /opt/Python-3.9.16.1690578198/lib/python3.9/site-packages (from rpy2==3.5.14) (3.1.2)
Requirement already satisfied: tzlocal in /opt/Python-3.9.16.1690578198/lib/python3.9/site-packages (from rpy2==3.5.14) (4.3.1)
Requirement already satisfied: pycparser in /opt/Python-3.9.16.1690578198/lib/python3.9/site-packages (from cffi>=1.10.0->rpy2==3.5.14) (2.21)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/Python-3.9.16.1690578198/lib/python3.9/site-packages (from jinja2->rpy2==3.5.14) (2.1.3)
Requirement already satisfied: pytz-deprecation-shim in /opt/Python-3.9.16.1690578198/lib/python3.9/site-packages (from tzlocal->rpy2==3.5.14) (0.1.0.post0)
Requirement already satisfied: tzdata in /opt/Python-3.9.16.1690578198/lib/python3.9/site-packages (from pytz-deprecation-shim->tzlocal->rpy2==3.5.14) (2023.3)
Building wheels for collected packages: rpy2
  Building wheel for rpy2 (pyproject.toml) ... done
  Created wheel for rpy2: filename=rpy2-3.5.14-py3-none-any.whl size=220465 sha256=4f366c9bd3fed74934d92ed1dce42ec35bb6aa9759ec19f8d8bb54bae645be89
  Stored in directory: /tmp/pip-ephem-wheel-cache-_b6yjqux/wheels/0d/38/c9/d39e5237ca33d13d385e55a2668ddbd9db7ec1870a94956fc6
Successfully built rpy2
Installing collected packages: rpy2
Successfully installed rpy2-3.5.14

[user@test rpy2]$ pip3 list | grep rpy2
rpy2                         3.5.14

**Comment by lgautier** [comment] 2023-08-05 20:18
Thanks for try @steadmaj  (and pointing out that I provided an incorrect commit hash - I edited the comment to fix it).

This is indeed caused caused by removing the dependency on `distutils`. I spotted that one use of `distutils` was forgotten behind. This could use an unwanted negative interaction between `distutils` and `setuptools`. Does `rpy2` install with PR #1053 ?

**Comment by pur80a** [comment] 2023-08-10 11:21
```
git clone https://github.com/rpy2/rpy2
git checkout be8973cd3e5d962e1c7bdf507101959a54a12b91 # PR 1053
TD=$(mktemp -d) 
python3 setup.py install --prefix=$TD
/bin/ld: warning: libRblas.so, needed by /home/apps/R/4.3.1/lib64/R/lib/libR.so, not found (try using -rpath or -rpath-
```
Then I tried: 
```
git checkout master
python3 setup.py install --prefix=$TD
```
with same error. 
The following worked: 
```
git checkout 'RELEASE_3_5_12'
python3 setup.py install --prefix=$TD
```
```
git checkout be8973cd3e5d962e1c7bdf507101959a54a12b91 # PR 1053
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/apps/R/4.3.1/lib64/R/lib python3 setup.py install --prefix=$TD
```
```
git checkout master 
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/apps/R/4.3.1/lib64/R/lib python3 setup.py install --prefix=$TD
```
where `/home/apps/R/4.3.1/lib64/R/lib` is the location of `libRblas.so`. It is strange, that rpy2 v3.5.13 does not find `libRblas.so`, but 3.5.12 finds it or doesn't need it.

**Comment by lgautier** [comment] 2023-09-02 21:00
PR #1053 removed direct use of `distutils` that was left behind when moving to `setuptools`. Does rpy2-3.5.14 (released this week) solve the issue?

**Comment by pur80a** [comment] 2023-09-09 18:47
yes, thanks! 
I think this issue can be closed.

**Closed** 2023-09-09 19:55 UTC
Labels: bug
