### ISSUE TITLE
Use both rpy2 and reticulate in python

### ISSUE THREAD

**Issue by liuzj039** [rpy2/rpy2#805] opened 2021-05-11 15:54 UTC
Thanks  developers for providing such a great tool.
I'm trying to use some packages that utilizes reticulate in python using rpy2.
Unfortunately, this will cause the kernel to stop.
I note that there has been a lot of discussion about this phenomenon.
The latest developments seem to be here. https://github.com/rstudio/reticulate/issues/208#issuecomment-808905814
However, when I update reticulate and use the following code in python, it still causes the kernel to stop. 
```import rpy2.robjects as ro # rpy2 version 3.3.6
from rpy2.robjects.packages import importr
R = ro.r
importr('reticulate') # reticulate version 1.20
R('use_python("/usr/local/bin/python")')
R("import('re')")
```
I would like to know if there are any solutions to this problem now?

Thank you. Hope for you answer!

**Comment by lgautier** [comment] 2021-05-13 02:59
The last activity about it I know about is the issue 208 you point out to. My understanding of the discussion is that there is a patch yet to be submitted.

**Comment by liuzj039** [comment] 2021-05-13 06:36
Thanks for the quick reply from the developer. 
Wish the subsequent version update can solve the compatibility issue.

**Comment by lgautier** [comment] 2021-05-13 23:40
The issue is on the `reticulate` side not the `rpy2`. Closing (it  here).

**Closed by lgautier** 2021-05-13 23:40 UTC
