### ISSUE TITLE
Conversion from R arrays to Python is very slow. 

### ISSUE THREAD

**Issue by vnmabus** [rpy2/rpy2#962] opened 2022-12-08 11:06 UTC
**Is your feature request related to a problem? Please describe.**
The conversion from a R array (such as a FloatSexpVector) to numpy always makes a copy. Thus, passing large arrays between R and Python is very slow.

**Describe the solution you'd like**
I would want that the conversion of the data is zero-copỳ if possible, using the Python buffer protocol.

**Comment by lgautier** [comment] 2022-12-11 15:07
The buffer protocol can be used when possible. See the doc: https://rpy2.github.io/doc/v3.5.x/html/numpy.html#low-level-interface

For other types of arrays this is a duplicate of issue #737 .

Finally, consider using `rpy2-arrow`: https://github.com/rpy2/rpy2-arrow. The conversion can be up to 200x faster with it.

**Closed by lgautier** 2022-12-11 15:07 UTC
Labels: enhancement

**Comment by vnmabus** [comment] 2022-12-11 21:09
The thing is that the conversion from `FloatSexpVector` is done via `numpy.array` and thus always make a copy. Is it not possible to do a zero-copy conversion?
