### ISSUE TITLE
Implicit numpy conversion in local context

### ISSUE THREAD

**Issue by nicole-brewer** [rpy2/rpy2#785] opened 2021-03-16 14:57 UTC
Version '3.4.2'
From a jupyter notebook

I'm trying to use a context manager to use the `numpy2ri.converter` as follows:
```python
import rpy2.robjects as ro
import rpy2.robjects.conversion as cv

with cv.localconverter(ro.numpy2ri.converter):
    obj = ro.r('c(1:4)')
    display(obj)
```
and got `NotImplementedError: Conversion 'rpy2py' not defined for objects of type '<class 'numpy.ndarray'>'` from line 200 of rpy2/robjects/conversion.py in _rpy2py(obj).

So I played around with pandas - which has a good example of local conversion in the docs - to make sure I understood the expected behavior.
```python
obj = ro.r('c(1:4)')
with cv.localconverter(ro.numpy2ri.converter):
    obj = ro.conversion.rpy2py(obj)
    display(obj)
```

This works, but I also wanted to know if I had to be explicit about calling `ro.conversion.rpy2py`, and I was happy to find out that I don't, i.e., this still automatically converts the data frame.
```python
with cv.localconverter(ro.default_converter + ro.pandas2ri.converter):
    r_from_pd_df = ro.r('data.frame(x = 4:6, y = c("a", "b", "c"))')
```

This is exactly what I would like to achieve with numpy. I was hoping it would function in a similar way, but to no avail. I changed the code so that I called the conversion function explicitly, as follows.

```python
obj = ro.r('c(1:4)')
with cv.localconverter(ro.numpy2ri.converter):
    obj = ro.conversion.rpy2py(obj)
```

This works, but it really isn't really all that useful. The traceback (for the original codeblock) makes be think that somehow the conversion in getting called twice, and that the second attempt throws an error because it's trying to convert something that's already been converted to a numpy array. I have tried this with numpy2ri both activated and deactivated in the global context to no avail. 

```python
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-50-8cc35b140e36> in <module>
      2 print(type(obj))
      3 with cv.localconverter(numpy2ri.converter):
----> 4     obj = ro.r('c(1:4)')
      5     obj = ro.conversion.rpy2py(obj)
      6     display(obj)

~/miniconda3/envs/superpower/lib/python3.9/site-packages/rpy2/robjects/__init__.py in __call__(self, string)
    437         p = rinterface.parse(string)
    438         res = self.eval(p)
--> 439         return conversion.rpy2py(res)
    440 
    441 

~/miniconda3/envs/superpower/lib/python3.9/functools.py in wrapper(*args, **kw)
    875                             '1 positional argument')
    876 
--> 877         return dispatch(args[0].__class__)(*args, **kw)
    878 
    879     funcname = getattr(func, '__name__', 'singledispatch function')

~/miniconda3/envs/superpower/lib/python3.9/site-packages/rpy2/robjects/conversion.py in _rpy2py(obj)
    198     non-rpy2) objects.
    199     """
--> 200     raise NotImplementedError(
    201         "Conversion 'rpy2py' not defined for objects of type '%s'" %
    202         str(type(obj))

NotImplementedError: Conversion 'rpy2py' not defined for objects of type '<class 'numpy.ndarray'>'
```

**Comment by nicole-brewer** [comment] 2021-03-16 14:59
When I run...
```python
obj = ro.r('c(1:4)')
print(type(obj))
```
... in the global scope I get `<class 'rpy2.robjects.vectors.IntVector'>` just like I'm supposed to

**Comment by nicole-brewer** [comment] 2021-03-16 23:59
I wasn't able to make any headway on the problem, but I was able to maneuver around it somewhat by creating my own converter.

```python
numpy_converter = conversion.Converter('numpy converter')
@numpy_converter.rpy2py.register(robjects.IntVector)
def to_numpy(obj):
    return robjects.numpy2ri.converter.rpy2py(obj)

with conversion.localconverter(numpy_converter + robjects.default_converter):
    obj = robjects.r('c(1:4)')
```

**Comment by nicole-brewer** [comment] 2021-03-17 00:41
It wouldn't fix the double call, but adding 

```python
@rpy2py.register(numpy.ndarray)
def rpy2py_ndarray(obj):
    return obj
```
to robjects/numpy2ri.py should easily patch the issue.

**Comment by lgautier** [comment] 2021-03-18 02:50
The `numpy` and `pandas` are written to be additions to a base converter. By default it is `default_converter`.

The following just works on this end:

```python
with cv.localconverter(ro.default_converter + ro.numpy2ri.converter):
    obj = ro.r('c(1:4)')
    display(obj)
```

**Comment by nicole-brewer** [comment] 2021-03-18 14:30
Oh I see. So then geting back a robjects.IntVector is the expected outcome?  I was expecting a numpy array and thought the default converter was overwriting numpy2pi.converter when I ran them together.

**Comment by lgautier** [comment] 2021-03-19 02:34
Oh. You are right, the numpy converter should return a numpy array. I just looked at whether an exception was raised. 
The converter is missing a couple of conversion rules.

**Comment by lgautier** [comment] 2021-03-19 03:45
PR merged. The fix will be included in release 3.4.3. Thanks for the issue report.

**Comment by nicole-brewer** [comment] 2021-03-22 17:09
I don't know if I should make a new issue or leave it here, but I actually would like to be able to use this converter as mentioned above.

```python
#@converter.rpy2py.register(rinterface.NULLType)
def rpy2py_null(obj):
    return None
```
to get None back from
```python
with localconverter(ro.default_converter + converter):
    obj = ro.r('NULL')
    display(obj)
```
but then when I run
```python
with conversion.localconverter(robjects.default_converter + converter) as cv:
    obj = cv.py2rpy(["mixed", 1, True])
    display(obj)
```
I get an error presumably because the 'names' attribute of obj is None instead of rinterface.NULL.
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/miniconda3/envs/superpower/lib/python3.9/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~/miniconda3/envs/superpower/lib/python3.9/site-packages/rpy2/robjects/vectors.py in _repr_html_(self, max_items)
    694         rnames = self.names
    695         if len(self) <= max_items:
--> 696             names.extend(
    697                 rnames
    698                 if rnames != rinterface.NULL

TypeError: 'NoneType' object is not iterable

<rpy2.robjects.vectors.ListVector object at 0x143e99d40> [RTYPES.VECSXP]
R classes: ('list',)
[StrSexpVector, IntSexpVector, BoolSexpVector]
  <no name>: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x143eac8c0> [RTYPES.STRSXP]
  <no name>: <class 'rpy2.rinterface.IntSexpVector'>
  <rpy2.rinterface.IntSexpVector object at 0x143eacb80> [RTYPES.INTSXP]
  <no name>: <class 'rpy2.rinterface.BoolSexpVector'>
  <rpy2.rinterface.BoolSexpVector object at 0x143eac8c0> [RTYPES.LGLSXP]
```
Do you have any thoughts on how to implement the desired behavior without causing an error? Thanks

**Comment by lgautier** [comment] 2021-03-27 14:23
The behavior you'd like to have should be expected to work since the reverse conversion (from `None` to R `NULL`) is already there:

```python
import rpy2.rinterface as ri
ri.initr()
ri.globalenv['x'] = None
print(ri.globalenv['x'])
# R NULL here
```
There is likely an other buglet in rpy2 here.

**Comment by lgautier** [comment] 2021-03-27 14:32
I believe that the issue was fixed with rpy2-3.4.3. The following just works here:

```python
import rpy2.robjects as ro
import rpy2.robjects.conversion as conversion

converter = conversion.Converter('foo')

@converter.rpy2py.register(ri.NULLType)
    def rpy2py_null(obj):
        return None 

with conversion.localconverter(ro.default_converter + converter) as cv:
    obj = cv.py2rpy(["mixed", 1, True])
    display(obj)
```

Do not hesiate to reopen if the issue is still present after upgrading to the latest rpy2 release.

**Closed by lgautier** 2021-03-27 14:32 UTC

**Comment by nicole-brewer** [comment] 2021-03-29 01:01
I updated and checked the version with  `rpy2.__version__` in a fresh notebook and the stand alone example you posted above, and no such luck. Same errror

**Comment by lgautier** [comment] 2021-03-29 03:53
I did check again, making sure I have 3.4.3 (I also have various dev versions instaled sometimes) and fixing 2 typos in the standalone exemple. It is it working on this end. I am using Python 3.8 but I would not expect a difference (Python 3.9 is included in the test matrix on GitHub Actions).
