### ISSUE TITLE
GET request producing undefined behavior in Django + rpy2 (*** stack smashing detected ***: terminated)

### ISSUE THREAD

**Issue by davidshumway** [rpy2/rpy2#777] opened 2021-02-17 04:48 UTC
**Describe the issue or bug**

Running rpy2 within Django and seeing the following unexpected behavior:

https://stackoverflow.com/questions/66233870/get-request-producing-undefined-behavior-in-django-rpy2

**To Reproduce**

**Expected behavior**

**Error**

**Additional context**

Python 3.8.6
R version 4.0.3 (2020-10-10)

**Comment by krassowski** [comment] 2021-02-17 08:22
It looks like another duplicate of #769.

**Comment by davidshumway** [comment] 2021-02-17 16:09
> It looks like another duplicate of #769.

Interesting. I remember seeing one of the error messages from that issue briefly a few days ago:

```bash
R[write to console]: 

*** longjmp causes uninitialized stack frame ***: terminated
Aborted (core dumped)
```

**Comment by davidshumway** [comment] 2021-02-17 16:12
Here's another error that just appeared when re-opening the browser after a few hours:

```bash
[17/Feb/2021 16:07:08] "GET /static/css/fontawesome.min.css HTTP/1.1" 200 50397
[17/Feb/2021 16:07:08] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 144877
[17/Feb/2021 16:07:08] "GET /static/css/main.css HTTP/1.1" 200 1826
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51686)
Traceback (most recent call last):
  File "/usr/lib64/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/dave/Dev/maldi-django/venv/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/dave/Dev/maldi-django/venv/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib64/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /favicon.ico
[17/Feb/2021 16:07:14] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 144877
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51840)
Traceback (most recent call last):
  File "/usr/lib64/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/dave/Dev/maldi-django/venv/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/dave/Dev/maldi-django/venv/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib64/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /favicon.ico
```

**Comment by lgautier** [comment] 2021-04-24 21:49
Issue #769 was fixed and the fix is included in the latest rpy2 release. Did it also fix this issue?

**Comment by lgautier** [comment] 2023-04-22 19:22
Assuming that it was fixed since no additional comment.

**Closed by lgautier** 2023-04-22 19:22 UTC
Labels: bug
