### ISSUE TITLE
'rpy2.rinterface.SexpClosure' errors reported on SO

### ISSUE THREAD

**Issue by tikuma-lsuhsc** [rpy2/rpy2#952] opened 2022-10-25 20:48 UTC
You may have already seen these, but recently on SO, there are a several issues raised with the same error message:

```
"NotImplementedError: Conversion 'rpy2py' not defined for objects of type '<class 'rpy2.rinterface.SexpClosure'>'".
```

https://stackoverflow.com/questions/74192490/rpy2-error-depends-on-execution-method-notimplementederror-conversion-rpy2py
https://stackoverflow.com/questions/74127941/error-when-django-import-rpy2-but-ok-with-single-python-file-notimplementederro
https://stackoverflow.com/questions/73831827/notimplementederror-conversion-rpy2py-not-defined-for-objects-of-type-class

I thought these are an issue with the R package they are using, but the most recent (the first link) claims that the error was raised by simply `importr`ing `base` and/or `utils` immediately after importing `rpy2`. This could be a Windows issue but I cannot reproduce it. Any ideas?

**Comment by slieped** [comment] 2022-10-26 10:23
I do have the same error as in the first post. But in my case, it only happens in jupyter notebooks.
I made several tests, and these are my outcomes:

1) if importing and running in the **SAME** cell, everything works fine **ONLY** the first run 

2) if importing rpy2 and running `importr` in DIFFERENT cell, I get the same error

3) This error only occurs on jupyter notebooks. Running several permutations on ipython works like a charm.

It seems that, on jupyter notebook, you can only make one instance of an robject (i.e one run of a cell).. after that, everything breaks.

Code:
`import rpy2.robjects as robjects`
`print(tmpr['pi'][0])`

OS: Pop_OS! 20.04 and Ubuntu 20.04
rpy2 version:  v3.5.5, and v3.5.4

**Comment by slieped** [comment] 2022-10-26 10:28
I just tried with an even older version v3.4.2, and the issue is solved...

let me know if you want me to make further tests!

**Comment by tikuma-lsuhsc** [comment] 2022-10-26 14:49
@slieped - Thanks for the tip. I relayed it to the SO. 

@lgautier - There is a new post there reporting a similar issue (but with `['<class 'str'>]`) when used with Django, claimed to work fine in standalone Python. Maybe a related issue?

https://stackoverflow.com/questions/74206306/rpy2-error-in-django-conversion-py2rpy-not-defined-for-objects-of-type-cla

**Comment by lgautier** [comment] 2022-10-27 02:52
I can reproduce. This seems to be only with jupyter. This almost certainly has to do with the converter/conversion rules between Python and R objects.

**Comment by lgautier** [comment] 2022-10-29 17:49
This is really weird. The converter is modified during the execution of a (the first cell).

For example, this a first cell and its output.

```python
import rpy2.robjects.conversion
print(rpy2.robjects.conversion.get_conversion())
```
```
<class 'rpy2.robjects.conversion.Converter'>
py2rpy
- builtins.object
- rpy2.rinterface._MissingArgType
- builtins.bool
- builtins.int
- builtins.float
- builtins.bytes
- builtins.str
- rpy2.robjects.robject.RObject
- rpy2.rinterface_lib.sexp.Sexp
- array.array
- builtins.list
- rpy2.rlike.container.TaggedList
- builtins.complex
- builtins.function
---
rpy2py
- builtins.object
- rpy2.robjects.robject.RObject
- rpy2.rinterface.IntSexpVector
  - factor (in rpy2.robjects.vectors)
- rpy2.rinterface.FloatSexpVector
  - Date (in rpy2.robjects.vectors)
  - POSIXct (in rpy2.robjects.vectors)
- rpy2.rinterface.ComplexSexpVector
- rpy2.rinterface.BoolSexpVector
- rpy2.rinterface_lib.sexp.StrSexpVector
- rpy2.rinterface.ByteSexpVector
- rpy2.rinterface.PairlistSexpVector
- rpy2.rinterface.LangSexpVector
- rpy2.rinterface.SexpClosure
- rpy2.rinterface_lib.sexp.SexpEnvironment
- rpy2.rinterface.ListSexpVector
  - data.frame (in rpy2.robjects.vectors)
- rpy2.rinterface.SexpS4
- rpy2.rinterface.SexpExtPtr
- rpy2.rinterface_lib.sexp.NULLType
---
```

This is a second cell and its output. The converter is gone.

```python
print(rpy2.robjects.conversion.get_conversion())

<class 'rpy2.robjects.conversion.Converter'>
py2rpy
- builtins.object
---
rpy2py
- builtins.object
```

This is not the case in `ipython`.

**Comment by lgautier** [comment] 2022-10-29 17:55
`rpy2` is keeping the active conversion rules in a `contextvars`.
This seems similar to this issue ( https://github.com/ipython/ipython/issues/11565 ), although the issue is marked as closed.

**Comment by tikuma-lsuhsc** [comment] 2022-10-29 17:57
Well, at least in Windows (Python 3.9.7, running from vscode), your code returns full converter def each time:

```python
Unable to determine R home: [WinError 2] The system cannot find the file specified
Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data[ in a text editor](command:workbench.action.openLargeOutput?4a982d9b-f4c1-4782-9a90-6a8e1660abde)
<class 'rpy2.robjects.conversion.Converter'>
py2rpy
- builtins.object
- rpy2.rinterface._MissingArgType
- builtins.bool
- builtins.int
- builtins.float
- builtins.bytes
- builtins.str
- rpy2.robjects.robject.RObject
- rpy2.rinterface_lib.sexp.Sexp
- array.array
- builtins.list
- rpy2.rlike.container.TaggedList
- builtins.complex
- builtins.function
---
rpy2py
- builtins.object
- rpy2.robjects.robject.RObject
- rpy2.rinterface.IntSexpVector
  - factor (in rpy2.robjects.vectors)
- rpy2.rinterface.FloatSexpVector
  - Date (in rpy2.robjects.vectors)
  - POSIXct (in rpy2.robjects.vectors)
...
- rpy2.rinterface.SexpS4
- rpy2.rinterface.SexpExtPtr
- rpy2.rinterface_lib.sexp.NULLType
---
Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data[ in a text editor](command:workbench.action.openLargeOutput?6884ab04-ba22-44ab-bfa2-4270476e85e6)
<class 'rpy2.robjects.conversion.Converter'>
py2rpy
- builtins.object
- rpy2.rinterface._MissingArgType
- builtins.bool
- builtins.int
- builtins.float
- builtins.bytes
- builtins.str
- rpy2.robjects.robject.RObject
- rpy2.rinterface_lib.sexp.Sexp
- array.array
- builtins.list
- rpy2.rlike.container.TaggedList
- builtins.complex
- builtins.function
---
rpy2py
- builtins.object
- rpy2.robjects.robject.RObject
- rpy2.rinterface.IntSexpVector
  - factor (in rpy2.robjects.vectors)
- rpy2.rinterface.FloatSexpVector
  - Date (in rpy2.robjects.vectors)
  - POSIXct (in rpy2.robjects.vectors)
...
- rpy2.rinterface.SexpS4
- rpy2.rinterface.SexpExtPtr
- rpy2.rinterface_lib.sexp.NULLType
---
```

**Comment by lgautier** [comment] 2022-10-29 17:59
This is an issue with jupyter/jupterlab's execution of cells with ipykernel. Upgrading `ipykernel` solves the issue.

**Closed by lgautier** 2022-10-29 17:59 UTC
Labels: bug
