### ISSUE TITLE
UserWarning when package is imported

### ISSUE THREAD

**Issue by jbschiratti** [rpy2/rpy2#732] opened 2020-09-18 10:06 UTC
Whenever I import pymer4, I have the following warning:

`UserWarning: R object inheriting from "POSIXct" but without attribute "tzone".`

How can I get rid of this warning?

macOS 10.15.5
pymer4==0.7.0
rpy2==3.3.5
R version 4.0.2

**Comment by lgautier** [comment] 2020-09-19 19:57
If the warning occurs when importing the Python package `pymer4`, I suggest inquiring about it with the authors of that package.

**Comment by lgautier** [comment] 2020-09-19 19:58
Closing as not directly an rpy2 issue. Reopen if it turns out the be an issue with rpy2.

**Closed by lgautier** 2020-09-19 19:58 UTC

**Comment by hermidalc** [comment] 2021-05-18 14:34
This is an rpy2 issue I believe, I'm getting the same thing `python 3.8.10`, `rpy2 3.4.4`, and `R 4.0.5`. It only seems to happen if I use `r_embedded.set_initoptions()`

Here's how to reproduce:
```python
import numpy as np
import pandas as pd
import rpy2.rinterface_lib.embedded as r_embedded

r_embedded.set_initoptions(
    ('rpy2', '--quiet', '--no-save', '--max-ppsize=500000'))

import rpy2.robjects as robjects
from rpy2.robjects import numpy2ri, pandas2ri
from rpy2.robjects.packages import importr

numpy2ri.activate()
pandas2ri.activate()

r_base = importr('base')
/home/hermidalc/soft/miniconda3/envs/tcga-cell-expression-prediction/lib/python3.8/site-packages/rpy2/robjects/vectors.py:980: UserWarning: R object inheriting from "POSIXct" but without attribute "tzone".
  warnings.warn('R object inheriting from "POSIXct" but without '
```

If I don't use `r_embedded.set_initoptions()` then I don't get the warning.

**Comment by hermidalc** [comment] 2022-01-13 16:04
Sorry to ping on this again, but is setting a larger `--max-ppsize` via `r_embedded.set_initoptions()` not useful or required anymore when using `R` >= 4.0?
