### ISSUE TITLE
symbol .env in the package "rlang" is conflicting

### ISSUE THREAD

**Issue by elgalu** [rpy2/rpy2#632] opened 2020-01-28 14:23 UTC
Hello,

There seems to be a problem with the new version of this package and rlang: https://github.com/r-lib/rlang/issues/904

RLang Version [0.4.3](https://github.com/r-lib/rlang/releases/tag/v0.4.3) introduced the following bug, when interacting with rpy2

```sh
Rscript -e "library('rlang')"
python -c "from rpy2.robjects.packages import importr; print(importr('rlang'))"
```

Now yields:

```py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/rpy2/robjects/packages.py", line 492, in importr
    symbol_resolve=symbol_resolve)
  File "/opt/conda/lib/python3.6/site-packages/rpy2/robjects/packages.py", line 204, in __init__
    self.__fill_rpy2r__(on_conflict=on_conflict)
  File "/opt/conda/lib/python3.6/site-packages/rpy2/robjects/packages.py", line 330, in __fill_rpy2r__
    .__fill_rpy2r__(on_conflict=on_conflict))
  File "/opt/conda/lib/python3.6/site-packages/rpy2/robjects/packages.py", line 255, in __fill_rpy2r__
    ' a Python object attribute')

rpy2.robjects.packages.LibraryError: The symbol .env in the package "rlang" is conflicting with a Python object attribute
```

Works fine when I rollback to [v0.4.2](https://github.com/r-lib/rlang/releases/tag/v0.4.2)

Python: 3.6.10
R: 3.6.2

**Comment by lgautier** [comment] 2020-01-28 17:33
Duplicate of #631. Update to latest rpy2 release.

**Closed by lgautier** 2020-01-28 17:33 UTC
Labels: duplicate
