### ISSUE TITLE
fail to import rpy2.robjects because of "different internals" of R versions

### ISSUE THREAD

**Issue by SivanYair** [rpy2/rpy2#714] opened 2020-07-02 01:03 UTC
Hello, I have an issue in which I can import rpy2 but fail to import rpy2.robjects:
`import rpy2.robjects`

> During startup - Warning messages:
> 1: package "methods" in options("defaultPackages") was not found    
> 2: package ‘utils’ in options("defaultPackages") was not found 
> 3: package ‘grDevices’ in options("defaultPackages") was not found 
> 4: package ‘graphics’ in options("defaultPackages") was not found 
> 5: package ‘stats’ in options("defaultPackages") was not found 
> 6: package ‘methods’ in options("defaultPackages") was not found 
> R[write to console]: Failed with error:  
> R[write to console]: 
> R[write to console]: ‘package ‘tools’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version`

I am using rpy2 version 3.3.4, python version 3.7.6, and R version 3.4.3 installed using conda (`conda install -c conda-forge r-3.4.3`) 

If I type `options("defaultPackages")` in my R console, all of the packages said to be "not found" in the rpy2 error message are listed.

Any suggestions on how to resolve this? Is this related to shlib?

Thank you!

**Comment by lgautier** [comment] 2020-07-03 17:28
The error message suggests that there might be a version issue with R (e.g., rpy2 compiled against a different of R than the one found at runtime). Unfortunately, from the number of reports this seems to be the most frequent among `conda` users.

Try if you can get useful insights from running the following in a shell:
 
```
python -m rpy2.situation
```

**Comment by xhochy** [comment] 2020-07-23 10:05
Note that `conda-forge` is not building packages for R 3.4 since quite some time. Especially doesn't `conda-forge` have an `r` package but it should be named `r-base`. Also `rpy2=3.3.4` was never released on `conda-forge`, thus I would suggest to close this issue and try with newer/correct versions.

**Comment by lgautier** [comment] 2020-07-28 01:46
I am understanding that the issue seems to be caused by an older version of R on conda. I am closing this, but please reopen if not the case.

**Closed by lgautier** 2020-07-28 01:46 UTC
