### ISSUE TITLE
PEP 517 builds rpy2 fails to install on Windows

### ISSUE THREAD

**Issue by harrylojames** [rpy2/rpy2#1104] opened 2024-04-10 16:47 UTC
With 3.5.12 installing rpy2 works. However with 3.5.13 and above I get the following error. Perhaps related to https://github.com/rpy2/rpy2/issues/1084 

```
poetry add rpy2@3.5.13

Updating dependencies
Resolving dependencies... (4.2s)

Package operations: 0 installs, 1 update, 0 removals

  - Updating rpy2 (3.5.12 -> 3.5.13): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel

  test_pw_r.c
  LINK : fatal error LNK1181: cannot open input file 'R.lib'
  Traceback (most recent call last):
    File "C:\Users\hj6\AppData\Local\Temp\tmp1uklv475\.venv\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 508, in link
      self.spawn([self.linker] + ld_args)
    File "C:\Users\hj6\AppData\Local\Temp\tmp1uklv475\.venv\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 517, in spawn
      return super().spawn(cmd, env=env)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\hj6\AppData\Local\Temp\tmp1uklv475\.venv\Lib\site-packages\setuptools\_distutils\ccompiler.py", line 1041, in spawn
      spawn(cmd, dry_run=self.dry_run, **kwargs)
    File "C:\Users\hj6\AppData\Local\Temp\tmp1uklv475\.venv\Lib\site-packages\setuptools\_distutils\spawn.py", line 70, in spawn
      raise DistutilsExecError(
  distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30037\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "C:\Users\hj6\.local\pipx\venvs\poetry\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\hj6\.local\pipx\venvs\poetry\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\hj6\.local\pipx\venvs\poetry\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\hj6\AppData\Local\Temp\tmp1uklv475\.venv\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\hj6\AppData\Local\Temp\tmp1uklv475\.venv\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "C:\Users\hj6\AppData\Local\Temp\tmp1uklv475\.venv\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 124, in <module>
    File "<string>", line 118, in get_r_c_extension_status
    File "<string>", line 81, in get_c_extension_status
    File "C:\Users\hj6\AppData\Local\Temp\tmp1uklv475\.venv\Lib\site-packages\setuptools\_distutils\ccompiler.py", line 781, in link_executable
      self.link(
    File "C:\Users\hj6\AppData\Local\Temp\tmp1uklv475\.venv\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 510, in link
      raise LinkError(msg)
  distutils.errors.LinkError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30037\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181


  at ~\.local\pipx\venvs\poetry\Lib\site-packages\poetry\installation\chef.py:164 in _prepare
      160│
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│
      163│             if error is not None:
    → 164│                 raise error from None
      165│
      166│             return path
      167│
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with rpy2 (3.5.13) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "rpy2 (==3.5.13)"'.

```

**Comment by lgautier** [comment] 2024-04-20 18:44
I have the same issue in the CI pipeline to build on Windows (For example, https://github.com/rpy2/rpy2/actions/runs/8767010752/job/24059781091?pr=1054#step:6:24) . I am likely missing how to specify where the compiler or linker can find `R.lib`. If you ever find out how to do it please let me know.

**Comment by harrylojames** [comment] 2024-04-24 10:42
Hey appreciate your work on this package and glad to see this is reproduceable and captured in the CI pipeline. Looking at the changes between 3.5.12 and 3.5.13 my money would firstly be on situation.py and then on rinterface.py. Would love to be of more help but I'm afraid building packages is not something I am familiar with. 

https://github.com/rpy2/rpy2/compare/RELEASE_3_5_12...RELEASE_3_5_13

**Comment by Sinansi** [comment] 2024-12-24 14:24
I am trying to install rpy2 in a conda environment (code), on windows 10, using pip.
I get alot of warnings and errors during installation.
Then finally the installation fail.

(code) C:\Users\sinan>pip install rpy2

DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\certifi-2024.12.14-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\charset_normalizer-3.4.0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\contourpy-1.3.1-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\cycler-0.12.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\eodhd-1.0.31-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\fonttools-4.55.3-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\ibapi-10.33.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\idna-3.10-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\kiwisolver-1.4.7-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\markdown_it_py-3.0.0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\matlabengine-24.2.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\matplotlib-3.10.0-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\mdurl-0.1.2-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\numpy-2.2.0-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\pandas-2.2.3-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\pillow-11.0.0-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\pygments-2.18.0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\pyparsing-3.2.0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\python_dateutil-2.9.0.post0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\pytz-2024.2-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\requests-2.32.3-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\rich-13.9.4-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\six-1.17.0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\tvdatafeed-2.1.0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\tzdata-2024.2-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\urllib3-2.2.3-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\websockets-14.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\sinan\miniconda3\envs\code\lib\site-packages\websocket_client-1.8.0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
Collecting rpy2
  Using cached rpy2-3.5.17.tar.gz (220 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "C:\Users\sinan\miniconda3\envs\code\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\sinan\miniconda3\envs\code\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\sinan\miniconda3\envs\code\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\sinan\AppData\Local\Temp\pip-build-env-93c0katl\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\sinan\AppData\Local\Temp\pip-build-env-93c0katl\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "C:\Users\sinan\AppData\Local\Temp\pip-build-env-93c0katl\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 141, in <module>
        File "<string>", line 121, in get_r_c_extension_status
        File "<string>", line 83, in get_c_extension_status
        File "C:\Users\sinan\AppData\Local\Temp\pip-build-env-93c0katl\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 379, in compile
          self.initialize()
        File "C:\Users\sinan\AppData\Local\Temp\pip-build-env-93c0katl\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 289, in initialize
          vc_env = _get_vc_env(plat_spec)
                   ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\sinan\AppData\Local\Temp\pip-build-env-93c0katl\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 150, in _get_vc_env
          raise DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

(code) C:\Users\sinan>

**Comment by lgautier** [comment] 2024-12-24 15:21
Deprecations seem to be independent from rpy2 (and come from other packages).

WRT the compilation error, that's yet another one I have not seen. There is a PR where I am trying to get MingW to be used. I am unsuccessful so far: https://github.com/rpy2/rpy2/pull/1128. 

I am stuck with being unable to get the MingW linker used: https://github.com/rpy2/rpy2/issues/1124#issuecomment-2525264050

**Comment by Sinansi** [comment] 2024-12-24 16:22
I was able to install rpy2 on windows by specifying an older version of rpy2. All recent versions failed to install except version 3.5.12. 

The following command worked for me:
pip install rpy2==3.5.12

I have also installed Microsoft Build Tools for Visual Studio 2022.

**Comment by Lucyyang1991** [comment] 2024-12-26 09:18
`pip install rpy2==3.5.12`

work for me too!
my python is V3.12.7 and my R is V 4.3.1

**Comment by lgautier** [comment] 2024-12-28 04:49
With https://github.com/rpy2/rpy2/pull/1128 merged, building binaries in the API mode (the preferred mode) seems to be working. 

I uploaded binaries for Python 3.9 to 3.12 and the dev version of rpy2-3.6.0.  Building for Python 3.13 might work the same way but I have not tried yet.

To install for Python 3.9 to 3.12 the following should just work:
```
pip install -U --pre rpy2-rinterface rpy2-robjects
```

**Comment by Sinansi** [comment] 2024-12-28 05:40
I was able to install rpy2 version 3.6.0 using the command you provided on Windows 10 and python 3.12


`(rpynew) C:\Users\sinan>pip install -U --pre rpy2-rinterface rpy2-robjects
Collecting rpy2-rinterface
  Downloading rpy2_rinterface-3.6.0.dev1-cp312-cp312-win_amd64.whl.metadata (2.0 kB)
Collecting rpy2-robjects
  Downloading rpy2_robjects-3.6.0.dev1-py3-none-any.whl.metadata (3.3 kB)
Collecting cffi>=1.15.1 (from rpy2-rinterface)
  Using cached cffi-1.17.1-cp312-cp312-win_amd64.whl.metadata (1.6 kB)
Collecting packaging (from rpy2-rinterface)
  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting jinja2 (from rpy2-robjects)
  Using cached jinja2-3.1.5-py3-none-any.whl.metadata (2.6 kB)
Collecting tzlocal (from rpy2-robjects)
  Using cached tzlocal-5.2-py3-none-any.whl.metadata (7.8 kB)
Collecting pycparser (from cffi>=1.15.1->rpy2-rinterface)
  Using cached pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Collecting MarkupSafe>=2.0 (from jinja2->rpy2-robjects)
  Using cached MarkupSafe-3.0.2-cp312-cp312-win_amd64.whl.metadata (4.1 kB)
Collecting tzdata (from tzlocal->rpy2-robjects)
  Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Downloading rpy2_rinterface-3.6.0.dev1-cp312-cp312-win_amd64.whl (163 kB)
Downloading rpy2_robjects-3.6.0.dev1-py3-none-any.whl (116 kB)
Using cached cffi-1.17.1-cp312-cp312-win_amd64.whl (181 kB)
Using cached jinja2-3.1.5-py3-none-any.whl (134 kB)
Using cached packaging-24.2-py3-none-any.whl (65 kB)
Using cached tzlocal-5.2-py3-none-any.whl (17 kB)
Using cached MarkupSafe-3.0.2-cp312-cp312-win_amd64.whl (15 kB)
Using cached pycparser-2.22-py3-none-any.whl (117 kB)
Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
Installing collected packages: tzdata, pycparser, packaging, MarkupSafe, tzlocal, jinja2, cffi, rpy2-rinterface, rpy2-robjects
Successfully installed MarkupSafe-3.0.2 cffi-1.17.1 jinja2-3.1.5 packaging-24.2 pycparser-2.22 rpy2-rinterface-3.6.0.dev1 rpy2-robjects-3.6.0.dev1 tzdata-2024.2 tzlocal-5.2

(rpynew) C:\Users\sinan>conda list
# packages in environment at C:\Users\sinan\miniconda3\envs\rpynew:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h2bbff1b_6
ca-certificates           2024.11.26           haa95532_0
cffi                      1.17.1                   pypi_0    pypi
expat                     2.6.4                h8ddb27b_0
jinja2                    3.1.5                    pypi_0    pypi
libffi                    3.4.4                hd77b12b_1
markupsafe                3.0.2                    pypi_0    pypi
openssl                   3.0.15               h827c3e9_0
packaging                 24.2                     pypi_0    pypi
pip                       24.2            py312haa95532_0
pycparser                 2.22                     pypi_0    pypi
python                    3.12.8               h14ffc60_0
rpy2-rinterface           3.6.0.dev1               pypi_0    pypi
rpy2-robjects             3.6.0.dev1               pypi_0    pypi
setuptools                75.1.0          py312haa95532_0
sqlite                    3.45.3               h2bbff1b_0
tk                        8.6.14               h0416ee5_0
tzdata                    2024.2                   pypi_0    pypi
tzlocal                   5.2                      pypi_0    pypi
vc                        14.40                haa95532_2
vs2015_runtime            14.42.34433          h9531ae6_2
wheel                     0.44.0          py312haa95532_0
xz                        5.4.6                h8cc25b3_1
zlib                      1.2.13               h8cc25b3_1`

**Comment by lgautier** [comment] 2024-12-28 15:52
@Sinansi - Thanks. Good to hear that it does seem to install. Having to install `rpy2-rinterface` and `rpy2-robjects` is only temporary. `pip install rpy2` will be enough with the next dev release (and the final release) for 3.6.9.

Do not hesitate to report issues.

**Closed by lgautier** 2024-12-28 15:52 UTC
Labels: bug, Windows

**Comment by lgautier** [comment] 2024-12-29 03:51
A dev version with windows binary wheels should install with: 
```sh
pip install -U --pre rpy2
```

**Comment by Lucyyang1991** [comment] 2025-01-07 09:33
I think the problem is still not solved.
After dev rpy2 installed, I can not import the` rpy2.rinterface_lib.callbacks`
```
rpy2                              3.6.0.dev2
rpy2-rinterface                   3.6.0.dev2
rpy2-robjects                     3.6.0.dev2
```
```
from scipy import sparse
import rpy2
import rpy2.rinterface_lib.callbacks
import logging
# Ignore R warning messages
#Note: this can be commented out to get more verbose R output
rpy2.rinterface_lib.callbacks.logger.setLevel(logging.ERROR)
import anndata2ri
anndata2ri.activate()
%load_ext rpy2.ipython
```
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], [line 3](vscode-notebook-cell:?execution_count=1&line=3)
      [1](vscode-notebook-cell:?execution_count=1&line=1) from scipy import sparse
      [2](vscode-notebook-cell:?execution_count=1&line=2) import rpy2
----> [3](vscode-notebook-cell:?execution_count=1&line=3) import rpy2.rinterface_lib.callbacks
      [4](vscode-notebook-cell:?execution_count=1&line=4) import logging
      [5](vscode-notebook-cell:?execution_count=1&line=5) # Ignore R warning messages
      [6](vscode-notebook-cell:?execution_count=1&line=6) #Note: this can be commented out to get more verbose R output

ModuleNotFoundError: No module named 'rpy2.rinterface_lib.callbacks'
```

**Comment by lgautier** [comment] 2025-01-11 16:12
I very much suspect that your VS code notebook does not pick up or find the installed rpy2 package you'd like it to.

Can you run the following in a cell of the same VS code notebook after the error occurs? 
```python
import rpy2
print(rpy2.__path__)

from subprocess import check_output
_ = check_output('py -m pip list --outdated --format columns', shell=True)
print(_)
```
