### ISSUE TITLE
rpy2 prevents shutdown via Ctrl+C

### ISSUE THREAD

**Issue by yannikschaelte** [rpy2/rpy2#723] opened 2020-07-27 19:53 UTC
**Describe the issue or bug**

When importing `import rpy2.robjects` in a flask app (https://github.com/pallets/flask), I can no longer close the app by ctrl+c. I checked that it is this line that causes the error, but have absolutely no idea what is happening in the background. Any hints welcome, the problem can surely also be on flask side.

**To Reproduce**

```python
from flask import Flask
import rpy2.robjects

app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hi there!'
```
run via `export FLASK_APP={FILE}.py; flask run` and then try to ctrl+c in the command line.

**Additional context**
Flask 1.1.2, rpy2 3.3.5, python 3.8, in general latest package versions.

**Comment by lgautier** [comment] 2020-07-28 02:21
R and Python are competing to handle SIGINT (Ctrl+c).

I don't know how to get to Flask's default behavior when SIGINT is sent, but here is at least how to get Ctrl-c to end your Flask run (add this code right after `import rpy2.robjects`).

```
import signal
import sys

def signal_handler(sig, frame):
    print('Handling SIGINT with an exit.')
    sys.exit(0)
signal.signal(signal.SIGINT, signal_handler)
```

**Comment by yannikschaelte** [comment] 2020-07-28 07:58
Thanks @lgautier! That will suffice for me.

**Comment by yannikschaelte** [comment] 2020-08-04 09:39
I would like to shortly come back to this. In fact, the problem is not limited to flask, but whenever I run a python app, importing `rpy2.robjects` (though not using it) prevents the app from closing, which is a major disturbance for us currently. This behavior occurs with rpy2 3.3.5, it does not appear with 3.2.0, so apparently sth changed in between?

**Code to reproduce:**
```python
import rpy2.robjects

c = 0

while True:
    print("where are you", c)
    c += 1
```
run via `python file.py` and try to Ctrl+C it. It just keeps going.

Your above solution would solve this, but I am not sure whether adding this global override to all programs using rpy2 is the best idea ...

If importing rpy2.robjects directly is not the intended usage, we could think about changing that as well.

**Comment by lgautier** [comment] 2020-08-05 02:03
`import rpy2.robjects` will cause the embedded R to be initialized on import, and the rerouting of handling what Ctrl-C does happens during the R initialization, I think.

I would not have anticipated this to change between rpy2-3.2.0 and rpy2-3.3.5. Is the same version of R used in both cases?

**Comment by yannikschaelte** [comment] 2020-08-05 07:17
It is exactly between 3.2.7 and 3.3.0. Yes, in both cases R 3.6.3 is used.

**Comment by yannikschaelte** [comment] 2020-08-19 18:06
@lgautier do you have any suggestions?

**Comment by lgautier** [comment] 2020-08-20 00:04
Unfortunately I currently don't have any suggestion beside the workaround proposed.

I scanned a diff between the two versions and I did not see anything I could identify as the likely cause (I focused on changes in `rpy2/rinterface_lib`).

**Comment by yannikschaelte** [comment] 2020-08-20 05:45
Can you reproduce the error? If not, I will investigate e.g. my outdated R version.

**Comment by lgautier** [comment] 2020-10-10 02:22
I can indeed reproduce the issue.

Modifying the script to the following does restore Ctrl+C, although with an unexpected error `RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>`.

```python
import rpy2.robjects
import signal


def signal_handler(sig, frame):
    print('You pressed Ctrl+C!')
    sys.exit(0)


signal.signal(signal.SIGINT, signal_handler)
c = 0

while True:
    print("where are you", c)
    c += 1
```

**Comment by lgautier** [comment] 2020-10-10 02:29
The `RuntimeError` is also present without `rpy2.robjects`. At least this part is not caused by `rpy2`.

Otherwise it seems that the fix would be to call `signal.signal()` right after the embedded R is initialized with the signal handler:

```python
def signal_handler(sig, frame):
    raise KeyboardInterrupt()
```

**Comment by lgautier** [comment] 2020-10-10 02:35
That's not enough, unfortunately. When interrupting code in R (example below), the Python process ends with an `RRuntimeError`.

```python
rpy2.robjects.r('Sys.sleep(30)')
```

It looks like I do not have a workaround to having a custom handling of SIGINT set when R is initialized (hoping this is possible R's C-API). I really don't see what might have changed since rpy2-3.2.7 that would have created this issue.

**Comment by lgautier** [comment] 2020-10-10 04:03
A first fix is in revision 6cf728b0b1d1e503b4825594f95cf07d9c10dd7f

**Comment by lgautier** [comment] 2023-04-22 18:49
Ctrl+C is working (Python 3.10, R-4.2, rpy2-3.5.10).

**Closed by lgautier** 2023-04-22 18:49 UTC

**Comment by TauchmanD** [comment] 2024-02-15 16:23
Ctrl+C not working on (Python 3.11.1, R-4.3.2, rpy2-3.5.15)

**Comment by TauchmanD** [comment] 2024-02-15 16:24
Ctrl+C not working on (Python 3.11.1, R-4.3.2, rpy2-3.5.15)

**Comment by lgautier** [comment] 2024-02-17 16:29
> Ctrl+C not working on (Python 3.11.1, R-4.3.2, rpy2-3.5.15)

This might be because signal handling is modified by the code you are running after rpy2 is imported / the embedded R is initialized.

**Comment by TauchmanD** [comment] 2024-02-28 12:21
It doen't work even if I just import rpy2.robjects

```
import time

import rpy2.robjects

i = 0
try:
    while 1:
        print(i)
        i += 1
        time.sleep(1)
except KeyboardInterrupt:
    print("exiting the program")
```

if you delete ```import rpy2.robjects``` it works just fine
