### ISSUE TITLE
unused argument (useS4 = FALSE) error when tbl_graph is displayed on jupyterlab

### ISSUE THREAD

**Issue by gokceneraslan** [rpy2/rpy2#763] opened 2020-12-30 21:59 UTC
**Describe the issue or bug**

When I try to display an object of type `tbl_graph` (from tidygraph package) on jupyterlab using `rpy2.ipython` I get an error.

**To Reproduce**

Run the following code on jupyterlab:

```r
%%R

library(ggraph)
library(tidygraph)
as_tbl_graph(highschool) # tries to display the object
```

**Expected behavior**

From R:

<img width="295" alt="image" src="https://user-images.githubusercontent.com/1140359/103383007-27179d00-4abf-11eb-9de4-73efafddb5fa.png">

**Error**

```pytb
R[write to console]: Error in (function (x, n = NULL, width = NULL, n_extra = NULL)  : 
  unused argument (useS4 = FALSE)

---------------------------------------------------------------------------
RRuntimeError                             Traceback (most recent call last)
<ipython-input-23-f9ce4738bd6e> in <module>
----> 1 get_ipython().run_cell_magic('R', '', '\nlibrary(ggraph)\nlibrary(tidygraph)\nas_tbl_graph(highschool)\n')

~/.miniconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2380             with self.builtin_trap:
   2381                 args = (magic_arg_s, cell)
-> 2382                 result = fn(*args, **kwargs)
   2383             return result
   2384 

<decorator-gen-121> in R(self, line, cell, local_ns)

~/.miniconda3/lib/python3.8/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~/.miniconda3/lib/python3.8/site-packages/rpy2/ipython/rmagic.py in R(self, line, cell, local_ns)
    773                                                'consolewrite_print',
    774                                                self.write_console_regular))
--> 775                         cell_display(result, args)
    776                         text_output += self.flush()
    777 

~/.miniconda3/lib/python3.8/site-packages/rpy2/ipython/rmagic.py in CELL_DISPLAY_DEFAULT(res, args)
    108 
    109 def CELL_DISPLAY_DEFAULT(res, args):
--> 110     return ro.r.show(res)
    111 
    112 

~/.miniconda3/lib/python3.8/site-packages/rpy2/robjects/functions.py in __call__(self, *args, **kwargs)
    195                 v = kwargs.pop(k)
    196                 kwargs[r_k] = v
--> 197         return (super(SignatureTranslatedFunction, self)
    198                 .__call__(*args, **kwargs))
    199 

~/.miniconda3/lib/python3.8/site-packages/rpy2/robjects/functions.py in __call__(self, *args, **kwargs)
    123             else:
    124                 new_kwargs[k] = conversion.py2rpy(v)
--> 125         res = super(Function, self).__call__(*new_args, **new_kwargs)
    126         res = conversion.rpy2py(res)
    127         return res

~/.miniconda3/lib/python3.8/site-packages/rpy2/rinterface_lib/conversion.py in _(*args, **kwargs)
     42 def _cdata_res_to_rinterface(function):
     43     def _(*args, **kwargs):
---> 44         cdata = function(*args, **kwargs)
     45         # TODO: test cdata is of the expected CType
     46         return _cdata_to_rinterface(cdata)

~/.miniconda3/lib/python3.8/site-packages/rpy2/rinterface.py in __call__(self, *args, **kwargs)
    622                     error_occured))
    623             if error_occured[0]:
--> 624                 raise embedded.RRuntimeError(_rinterface._geterrmessage())
    625         return res
    626 

RRuntimeError: Error in (function (x, n = NULL, width = NULL, n_extra = NULL)  : 
  unused argument (useS4 = FALSE)

```

**Additional context**
R: 4.0.3
rpy2: 3.3.6 from conda-forge

**Comment by lgautier** [comment] 2021-01-01 17:33
The output of an R cell is using R's own `show()`. The equivalent of block you have under `%%R` can be reproduced in an R console with the following, and it fails with the same error:

```r
library(ggraph)
library(tidygraph)
show(
  as_tbl_graph(highschool)
)
```

R's own traceback points toward an issue with the code in the packages you are using. The function `tidygraph:::print.tbl_graph()` calls `tibble::trunc_mat()` while forwarding `useS4` (and `trunc_mat()` doesn't use it):

```r
> traceback()
6: do.call(trunc_mat, modifyList(arg_list, list(x = as_tibble(x), 
       n = 6)))
5: print.tbl_graph(object, useS4 = FALSE)
4: print(object, useS4 = FALSE)
3: showDefault(object)
2: show(x)
1: show(x)
```

While the issue is for the maintainers of `tidygraph` to solve, in the meantime you can do:

```r
library(ggraph)
library(tidygraph)
print(
  as_tbl_graph(highschool)
)
```

**Comment by lgautier** [comment] 2021-01-01 17:37
Not an rpy2 bug. Closing.

**Closed by lgautier** 2021-01-01 17:37 UTC
Labels: bug

**Comment by gokceneraslan** [comment] 2021-01-01 19:42
Thanks for the explanation! 🙏
