### ISSUE TITLE
issue with import `sagemaker` library

### ISSUE THREAD

**Issue by AlexanderKUA** [rpy2/rpy2#806] opened 2021-05-13 18:55 UTC
**Describe the issue or bug**

I got crash while tried to import `sagemaker` library on SageMaker instance.

**To Reproduce**

run this code in Jupyter notebook
```
import rpy2.robjects as robjects

print(robjects.r('''
library(reticulate)
sessionInfo()
sagemaker <- import('sagemaker')
'''))
```

**Expected behavior**
Should import properly.

**Error**
R[write to console]: 
 *** caught segfault ***

R[write to console]: address 0x10, cause 'memory not mapped'

R[write to console]: 
Traceback:

R[write to console]:  1: 
R[write to console]: py_initialize(config$python, config$libpython, config$pythonhome, 
R[write to console]:     config$virtualenv_activate, config$version >= "3.0", interactive(), 
R[write to console]:     numpy_load_error)
R[write to console]: 

R[write to console]:  2: 
R[write to console]: (function() {
R[write to console]:     Sys.setenv(PYTHONPATH = newpythonpath)
R[write to console]:     on.exit(Sys.setenv(PYTHONPATH = oldpythonpath), add = TRUE)
R[write to console]:     py_initialize(config$python, config$libpython, config$pythonhome, 
R[write to console]:         config$virtualenv_activate, config$version >= "3.0", 
R[write to console]:         interactive(), numpy_load_error)
R[write to console]: })()
R[write to console]: 
...

**Additional context**

env details:
rpy2 version: 3.4.4
---------------------
R version 3.6.3 (2020-02-29)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Amazon Linux AMI 2018.03

Matrix products: default
BLAS/LAPACK: /home/ec2-user/anaconda3/envs/python3/lib/libopenblasp-r0.3.12.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] tools     stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] reticulate_1.20

loaded via a namespace (and not attached):
[1] compiler_3.6.3  Matrix_1.3-3    Rcpp_1.0.6      grid_3.6.3     
[5] jsonlite_1.7.2  png_0.1-7       lattice_0.20-44

**Comment by lgautier** [comment] 2021-05-13 23:43
Duplicate of this, I think: https://github.com/rstudio/reticulate/issues/208#issuecomment-462155597

I am closing it here since the issue is not the rpy2 side.

**Closed by lgautier** 2021-05-13 23:43 UTC
Labels: bug
