### ISSUE TITLE
Error when Pip install rpy2

### ISSUE THREAD

**Issue by nmagdanz** [rpy2/rpy2#1049] opened 2023-07-21 03:07 UTC
Cannot install Rpy2 using Pip install rpy2.  Get the following error (no errors with other packages).

(base) PS C:\Windows\system32> pip install rpy2 --user
Collecting rpy2
  Using cached rpy2-3.5.13.tar.gz (218 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "C:\Users\nmagd\anaconda3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\nmagd\anaconda3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\nmagd\anaconda3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\nmagd\AppData\Local\Temp\pip-build-env-7bwn6qyw\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\nmagd\AppData\Local\Temp\pip-build-env-7bwn6qyw\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\nmagd\AppData\Local\Temp\pip-build-env-7bwn6qyw\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 124, in <module>
        File "<string>", line 110, in get_r_c_extension_status
        File "C:\Users\nmagd\AppData\Local\Temp\pip-install-uavjx8fv\rpy2_0ebf52157e104fdab38c514e3d30a9f1\./rpy2/situation.py", line 286, in get_r_flags
          _get_r_cmd_config(r_home, flags,
        File "C:\Users\nmagd\AppData\Local\Temp\pip-install-uavjx8fv\rpy2_0ebf52157e104fdab38c514e3d30a9f1\./rpy2/situation.py", line 246, in _get_r_cmd_config
          output = subprocess.check_output(
        File "C:\Users\nmagd\anaconda3\lib\subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\Users\nmagd\anaconda3\lib\subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\nmagd\anaconda3\lib\subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\nmagd\anaconda3\lib\subprocess.py", line 1456, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      PermissionError: [WinError 5] Access is denied
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Thanks for the help.

**Comment by GegznaV** [comment] 2023-07-29 17:28
I think this is a duplicate of
- #1045 

@nmagdanz, until the issue is fixed, try:
```bash
pip install rpy2==3.5.12
```

Does this solve your problem?

**Comment by lgautier** [comment] 2024-12-28 04:50
With https://github.com/rpy2/rpy2/pull/1128 merged, building binaries in the API mode (the preferred mode) seems to be working. 

I uploaded binaries for Python 3.9 to 3.12 and the dev version of rpy2-3.6.0.  Building for Python 3.13 might work the same way but I have not tried yet.

To install for Python 3.9 to 3.12 the following should just work:
```
pip install -U --pre rpy2-rinterface rpy2-robjects
```

**Comment by lgautier** [comment] 2024-12-30 20:24
Binary wheels for Windows are now built by the CI pipeline. Dev builds can be installed with:

```bash
pip install -U --pre rpy2
```

**Closed by lgautier** 2024-12-30 20:24 UTC
Labels: bug, Windows
