### ISSUE TITLE
can't install rpy2 3.5.16 on Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by sanboton** [rpy2/rpy2#1106] opened 2024-04-20 19:23 UTC
Describe the issue or bug

I can't install rpy2 3.5.16 on Ubuntu 22.04.3 LTS

To Reproduce

Open cmd as administrator

pip3 install rpy2 or pip install rpy2

Expected behavior
install rpy2

Error

```
pip3 install rpy2
Defaulting to user installation because normal site-packages is not writeable
Collecting rpy2
  Using cached rpy2-3.5.16.tar.gz (220 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 23, in <module>
          import setuptools.command.build
      ModuleNotFoundError: No module named 'setuptools.command.build'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by sanboton** [comment] 2024-04-20 19:24
I had to go down to version 3.5.2 to be able to install it

**Comment by lgautier** [comment] 2024-04-20 19:37
What is your version of `setuptools`?

**Comment by sanboton** [comment] 2024-04-20 20:14
Hi, it's 69.5.1.

```
pip3 show setuptools
Name: setuptools
Version: 69.5.1
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License:
Location: /home/NAME/.local/lib/python3.10/site-packages
Requires:
Required-by: APScheduler
```

**Comment by lgautier** [comment] 2024-04-20 20:58
I can't reproduce with Ubuntu 22.04, Python 3.10, and the same setuptools. It installs fine. What is your Python version?

**Comment by sanboton** [comment] 2024-04-21 08:59
My version is 3.10.12:

```
python3 -V
Python 3.10.12
```

**Comment by lgautier** [comment] 2024-04-21 17:22
The error traceback says that the path is `/usr/lib/python3/dist-packages/setuptools/build_meta.py` while `pip3 show setuptools` says that the path is `/home/NAME/.local/lib/python3.10/site-packages`.

**Comment by Hasnae12** [comment] 2024-05-01 17:22
> Describe the issue or bug
> 
> I can't install rpy2 3.5.16 on Ubuntu 22.04.3 LTS
> 
> To Reproduce
> 
> Open cmd as administrator
> 
> pip3 install rpy2 or pip install rpy2
> 
> Expected behavior install rpy2
> 
> Error
> 
> ```
> pip3 install rpy2
> Defaulting to user installation because normal site-packages is not writeable
> Collecting rpy2
>   Using cached rpy2-3.5.16.tar.gz (220 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
> 
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [16 lines of output]
>       Traceback (most recent call last):
>         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
>           main()
>         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
>           return hook(config_settings)
>         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
>           return self._get_build_requires(
>         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
>           self.run_setup()
>         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
>           exec(compile(code, __file__, 'exec'), locals())
>         File "setup.py", line 23, in <module>
>           import setuptools.command.build
>       ModuleNotFoundError: No module named 'setuptools.command.build'
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> ```

Hi, I have the same issue on Ubuntu 20.04.6 LTS

**Comment by lgautier** [comment] 2024-05-05 14:49
The last mentions

> Open cmd as administrator

while the traceback has

> ``` 
> Defaulting to user installation because normal site-packages is not writeable
> ```

There is a contradiction.

I believe that both error reports result from invalid assumptions by the operators about what Python+libraries are used, or the system ID  running the installation process.

**Comment by D3SL** [comment] 2024-05-11 00:07
Had this as well. Using `rocker/r2u:jammy` as a base I couldn't get the latest version of rpy2 to install, only 3.5.2.

**Comment by Yunuuuu** [comment] 2024-05-16 16:08
The same problem

**Comment by Yunuuuu** [comment] 2024-05-16 16:11
> Had this as well. Using `rocker/r2u:jammy` as a base I couldn't get the latest version of rpy2 to install, only 3.5.2.
> 
> Edit: I solved this with `RUN pip3 install --upgrade pip wheel setuptools>51` prior to trying to install rpy2.

This works well

**Comment by amano-takahisa** [comment] 2024-05-17 17:56
Same issues on Ubuntu 24.04.

To reproduce, build container with following `Dockerfile`:

```Dockerfile
FROM ubuntu:24.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    r-base \
    r-base-dev \
    python3 \
    python3-pip \
    python3-venv

USER ubuntu
WORKDIR /home/ubuntu
```

Build and enter the container with `docker build -t test_rpy2 . && docker run -it --rm test_rpy2 /bin/bash`, and in that container, run:

```bash
python3 -m venv .venv
source .venv/bin/activate
pip install -U pip setuptools 
pip install rpy2
```

Raise the following error.

<details>
<summary>Details</summary>
<pre>
$ pip install rpy2
Collecting rpy2
  Downloading rpy2-3.5.16.tar.gz (220 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 220.0/220.0 kB 8.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      /usr/bin/ld: cannot find -ltirpc: No such file or directory
      collect2: error: ld returned 1 exit status
      Traceback (most recent call last):
        File "/tmp/pip-build-env-3em6ull7/overlay/lib/python3.12/site-packages/setuptools/_distutils/unixccompiler.py", line 269, in link
          self.spawn(linker + ld_args)
        File "/tmp/pip-build-env-3em6ull7/overlay/lib/python3.12/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/tmp/pip-build-env-3em6ull7/overlay/lib/python3.12/site-packages/setuptools/_distutils/spawn.py", line 68, in spawn
          raise DistutilsExecError(f"command {cmd!r} failed with exit code {exitcode}")
      distutils.errors.DistutilsExecError: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/home/ubuntu/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/ubuntu/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/ubuntu/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-3em6ull7/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-3em6ull7/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-3em6ull7/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 141, in <module>
        File "<string>", line 121, in get_r_c_extension_status
        File "<string>", line 82, in get_c_extension_status
        File "/tmp/pip-build-env-3em6ull7/overlay/lib/python3.12/site-packages/setuptools/_distutils/ccompiler.py", line 781, in link_executable
          self.link(
        File "/tmp/pip-build-env-3em6ull7/overlay/lib/python3.12/site-packages/setuptools/_distutils/unixccompiler.py", line 271, in link
          raise LinkError(msg)
      distutils.errors.LinkError: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
</pre>

</details>

`pip install 'rpy2<=3.5.12'` worked, but not `pip install 'rpy2<=3.5.13'`.

**Comment by amano-takahisa** [comment] 2024-05-18 08:49
I solved my issue with installing `libtirpc-dev` beforehand.

**Comment by lgautier** [comment] 2024-05-24 16:45
> Had this as well. Using `rocker/r2u:jammy` as a base I couldn't get the latest version of rpy2 to install, only 3.5.2.
> 
> Edit: I solved this with `RUN pip3 install --upgrade pip wheel setuptools>51` prior to trying to install rpy2.

@D3SL  - This seems odd. rpy2 already requires setuptools>=61:
https://github.com/rpy2/rpy2/blob/ae74c26deca603786acfe0bdb03433bfc74975fc/pyproject.toml#L3

**Comment by amano-takahisa** [comment] 2024-05-28 15:13
@lgautier I'm not sure where that the header is required.
I just guessed from the following part of error message.
```
/usr/bin/ld: cannot find -ltirpc: No such file or directory
```

**Comment by lgautier** [comment] 2024-11-02 14:50
It looks to me that `libtirpc-dev` should be a dependency for `r-base-dev` (or whatever is the name of the package that provide R headers in your system's dependency manager). In that case it should be reported there.

I am closing for now. Reopen I missed something.

**Closed by lgautier** 2024-11-02 14:50 UTC
Labels: bug
