### ISSUE TITLE
errors intro to utils help_search

### ISSUE THREAD

**Issue by joh4nd** [rpy2/rpy2#1024] opened 2023-05-11 15:52 UTC
[reported on stackoverflow](https://stackoverflow.com/questions/76229906/rpy2-r-engine-in-python-cannot-find-keywords-db-utils-fails-searching-help)

**Describe the issue or bug**

python returns errors when [getting help with locating topics among available packages](https://rpy2.github.io/doc/latest/html/introduction.html#locate-topics-among-available-packages).

**To Reproduce**

System: Debian stable (bullseye)
R: r-base 4.0.4-1
Python: python3 3.9.2-3
rpy2: rpy2 3.4.2

```bash
$ sudo apt install r-base r-base-dev python3-rpy2

$ python
>>> import rpy2
>>> from rpy2.robjects.packages import importr 
>>> from rpy2.robjects import r
>>> rutils = importr('utils')
>>> rhelp_dox = rutils.help('help')
>>> rhelp_dox[0]
>>> str(rhelp_doc)
>>> rhelp_where = rutils.help_search("help")
```

_virtual environment_

virtualenv: python3-virtualenv 20.4.0+ds-20deb11u1

```bash
$ sudo apt install python3-virtualenv
$ pip install virtualenv # already installed

$ virtualenv venv
$ source ./venv/bin/activate

$ pip install rpy2==3.4.2 # version of python3-rpy2 from Debian repository

$ python
>>> import rpy2
>>> from rpy2.robjects.packages import importr 
>>> from rpy2.robjects import r
>>> rutils = importr('utils')
>>> rhelp_dox = rutils.help('help')
>>> rhelp_dox[0]
>>> str(rhelp_doc)
>>> rhelp_where = rutils.help_search("help")
```

**Expected behavior**
I expected the code from the instructions introduction to new users to not raise errors.

`help.search('help')` in the terminal returns the help interface, and in RStudio from the R console it returns items in the help pane. The help describes hsearch-utils and the **hsearch_db**

**Error**

_default environment_

```bash
>>> import rpy2
>>> from rpy2.robjects.packages import importr
>>> from rpy2.robjects import r
>>> rutils = importr('utils')
>>> rhelp_where = rutils.help_search('help')
R[write to console]: Error in file(con, "r") : cannot open the connection

R[write to console]: In addition: 
R[write to console]: Warning messages:

R[write to console]: 1: 
R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
R[write to console]: 
 
R[write to console]:  library ‘/usr/local/lib/R/site-library’ contains no packages

R[write to console]: 2: 
R[write to console]: In file(con, "r") :
R[write to console]: 
 
R[write to console]:  cannot open file '/usr/lib/R/doc/KEYWORDS.db': No such file or directory

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/path/to/venv/lib/python3.9/site-packages/rpy2/robjects/functions.py", line 198, in __call__
    return (super(SignatureTranslatedFunction, self)
  File "/home/path/to/venv/lib/python3.9/site-packages/rpy2/robjects/functions.py", line 125, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/home/path/to/venv/lib/python3.9/site-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/home/path/to/venv/lib/python3.9/site-packages/rpy2/rinterface.py", line 677, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in file(con, "r") : cannot open the connection

```

_virtual environment_

```bash
>>> rhelp_where = rutils.help_search("help")
R[write to console]: Error in file(con, "r") : cannot open the connection

R[write to console]: In addition: 
R[write to console]: Warning message:

R[write to console]: In file(con, "r") :
R[write to console]: 
 
R[write to console]:  cannot open file '/usr/lib/R/doc/KEYWORDS.db': No such file or directory

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/path/to/venv/lib/python3.9/site-packages/rpy2/robjects/functions.py", line 198, in __call__
    return (super(SignatureTranslatedFunction, self)
  File "/home/path/to/venv/lib/python3.9/site-packages/rpy2/robjects/functions.py", line 125, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/home/path/to/venv/lib/python3.9/site-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/home/path/to/venv/lib/python3.9/site-packages/rpy2/rinterface.py", line 677, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in file(con, "r") : cannot open the connection
```

_Please notice I edited the directory paths_ /path/to/

```bash
$ find / KEYWORDS.db # returns "No such file or directory"
```

**Additional context**
```bash
>>> for row in rpy2.situation.iter_info():
...     print(row)
... 
rpy2 version:
3.4.2
Python version:
3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
Looking for R's HOME:
    Environment variable R_HOME: /usr/lib/R
    Calling `R RHOME`: /usr/lib/R
    Environment variable R_LIBS_USER: None
R's additions to LD_LIBRARY_PATH:
/usr/lib/R/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server
R version:
    In the PATH: R version 4.0.4 (2021-02-15) -- "Lost Library Book"
    Loading R library from rpy2: OK
Additional directories to load R packages from:
None
C extension compilation:
  include:
  ['/usr/share/R/include']
  libraries:
  ['R', 'pcre2-8', 'lzma', 'bz2', 'z', 'rt', 'dl', 'm', 'icuuc', 'icui18n']
  library_dirs:
  ['/usr/lib/R/lib']
  extra_compile_args:
  []
  extra_link_args:
  ['-Wl,--export-dynamic', '-fopenmp', '-Wl,-z,relro']

```

```bash
>>> print(rutils.help_search)
function (pattern, fields = c("alias", "concept", "title"), apropos, 
    keyword, whatis, ignore.case = TRUE, package = NULL, lib.loc = NULL, 
    help.db = getOption("help.db"), verbose = getOption("verbose"), 
    rebuild = FALSE, agrep = NULL, use_UTF8 = FALSE, types = getOption("help.search.types")) 
{
    .wrong_args <- function(args) gettextf("argument %s must be a single character string", 
        sQuote(args))
    if (is.logical(verbose)) 
        verbose <- 2 * as.integer(verbose)
    fuzzy <- agrep
    if (!missing(pattern)) {
        if (!is.character(pattern) || (length(pattern) > 1L)) 
            stop(.wrong_args("pattern"), domain = NA)
        i <- pmatch(fields, hsearch_db_fields)
        if (anyNA(i)) 
            stop("incorrect field specification")
        else fields <- hsearch_db_fields[i]
    }
    else if (!missing(apropos)) {
        if (!is.character(apropos) || (length(apropos) > 1L)) 
            stop(.wrong_args("apropos"), domain = NA)
        else {
            pattern <- apropos
            fields <- c("alias", "title")
        }
    }
    else if (!missing(keyword)) {
        if (!is.character(keyword) || (length(keyword) > 1L)) 
            stop(.wrong_args("keyword"), domain = NA)
        else {
            pattern <- keyword
            fields <- "keyword"
            if (is.null(fuzzy)) 
                fuzzy <- FALSE
        }
    }
    else if (!missing(whatis)) {
        if (!is.character(whatis) || (length(whatis) > 1)) 
            stop(.wrong_args("whatis"), domain = NA)
        else {
            pattern <- whatis
            fields <- "alias"
        }
    }
    else {
        stop("do not know what to search")
    }
    if (!missing(help.db)) 
        warning("argument 'help.db' is deprecated")
    i <- pmatch(types, hsearch_db_types)
    if (anyNA(i)) 
        stop("incorrect type specification")
    else types <- hsearch_db_types[i]
    db <- hsearch_db(package, lib.loc, types, verbose, rebuild, 
        use_UTF8)
    lib.loc <- attr(db, "LibPaths")
    if (!identical(sort(types), sort(attr(db, "Types")))) {
        db$Base <- db$Base[!is.na(match(db$Base$Type, types)), 
            ]
        db[-1L] <- lapply(db[-1L], function(e) {
            e[!is.na(match(e$ID, db$Base$ID)), ]
        })
    }
    if (!is.null(package)) {
        pos_in_hsearch_db <- match(package, unique(db$Base[, 
            "Package"]), nomatch = 0L)
        if (any(pos_in_hsearch_db) == 0L) 
            stop(gettextf("no information in the database for package %s: need 'rebuild = TRUE'?", 
                sQuote(package[pos_in_hsearch_db == 0][1L])), 
                domain = NA)
        db[] <- lapply(db, function(e) {
            e[!is.na(match(e$Package, package)), ]
        })
    }
    if (verbose >= 2L) {
        message("Database of ", NROW(db$Base), " help objects (", 
            NROW(db$Aliases), " aliases, ", NROW(db$Concepts), 
            " concepts, ", NROW(db$Keywords), " keywords)", domain = NA)
        flush.console()
    }
    if (!length(db$Base)) 
        return(invisible())
    if (is.null(fuzzy) || is.na(fuzzy)) 
        fuzzy <- (grepl("^([[:alnum:]]|[[:space:]]|-)+$", pattern) && 
            (nchar(pattern, type = "c") > 4L))
    if (is.logical(fuzzy)) {
        if (fuzzy) 
            max.distance <- 0.1
    }
    else if (is.numeric(fuzzy) || is.list(fuzzy)) {
        max.distance <- fuzzy
        fuzzy <- TRUE
    }
    else stop("incorrect 'agrep' specification")
    dbBase <- db$Base
    search_fun <- if (fuzzy) {
        function(x) {
            agrep(pattern, x, ignore.case = ignore.case, max.distance = max.distance)
        }
    }
    else {
        function(x) {
            grep(pattern, x, ignore.case = ignore.case, perl = use_UTF8)
        }
    }
    search_db_results <- function(p, f, e) data.frame(Position = p, 
        Field = f, Entry = e, stringsAsFactors = FALSE)
    search_db_field <- function(field) {
        switch(field, alias = {
            aliases <- db$Aliases$Alias
            matched <- search_fun(aliases)
            search_db_results(match(db$Aliases$ID[matched], dbBase$ID), 
                rep.int(field, length(matched)), aliases[matched])
        }, concept = {
            concepts <- db$Concepts$Concept
            matched <- search_fun(concepts)
            search_db_results(match(db$Concepts$ID[matched], 
                dbBase$ID), rep.int(field, length(matched)), 
                concepts[matched])
        }, keyword = {
            keywords <- db$Keywords$Keyword
            matched <- search_fun(keywords)
            search_db_results(match(db$Keywords$ID[matched], 
                dbBase$ID), rep.int(field, length(matched)), 
                keywords[matched])
        }, name = {
            matched <- search_fun(dbBase$Name)
            search_db_results(matched, rep.int("Name", length(matched)), 
                dbBase$Name[matched])
        }, title = {
            matched <- search_fun(dbBase$Title)
            search_db_results(matched, rep.int("Title", length(matched)), 
                dbBase$Title[matched])
        })
    }
    matches <- NULL
    for (f in fields) matches <- rbind(matches, search_db_field(f))
    matches <- matches[order(matches$Position), ]
    db <- cbind(dbBase[matches$Position, c("Topic", "Title", 
        "Name", "ID", "Package", "LibPath", "Type"), drop = FALSE], 
        matches[c("Field", "Entry")])
    rownames(db) <- NULL
    if (verbose >= 2L) {
        n_of_objects_matched <- length(unique(db[, "ID"]))
        message(sprintf(ngettext(n_of_objects_matched, "matched %d object.", 
            "matched %d objects."), n_of_objects_matched), domain = NA)
        flush.console()
    }
    y <- list(pattern = pattern, fields = fields, type = if (fuzzy) "fuzzy" else "regexp", 
        agrep = agrep, ignore.case = ignore.case, types = types, 
        package = package, lib.loc = lib.loc, matches = db)
    class(y) <- "hsearch"
    y
}
<bytecode: 0x2d3e1e8>
<environment: namespace:utils>

```

**Comment by lgautier** [comment] 2023-05-14 18:10
I can't reproduce with latest rpy2 release (3.5.11 at the time of writing). The 3.4.x series is not longer maintained.

**Comment by joh4nd** [comment] 2023-05-15 11:44
Okay, thanks. Can you recommend a way of installing on Debian bullseye, the stable version? I installed via `apt`. Would you suggest updating the repository? Or would you recommend `pip` installing?

**Comment by lgautier** [comment] 2023-05-20 02:18
Pip is expected to work.

**Comment by lgautier** [comment] 2023-05-20 14:49
I am closing. Instructions to install are in the doc and the README (https://github.com/rpy2/rpy2#installation).

**Closed by lgautier** 2023-05-20 14:49 UTC
Labels: bug
