### ISSUE TITLE
BoolVector to array conversion behaves unexpectedly

### ISSUE THREAD

**Issue by arthus701** [rpy2/rpy2#1100] opened 2024-03-20 13:45 UTC
Thanks for a great package, it was a great experience working with it so far!

I realized, when converting a `BoolVector` to a `numpy.array` it is returned as `int32` array. I expected it to be `bool`. Not sure if this is intended, but I didn't find anything hinting at this in the docs...

Code to reproduce:

```python
>>> import numpy as np
>>> import rpy2.robjects as ro
>>> bool_vec = ro.BoolVector([True, False, True, False, False])
>>> np.array(bool_vec)
array([1, 0, 1, 0, 0], dtype=int32)
```
Of course a hotfix can be
```python
>>> np.array(bool_vec).astype(bool)
array([ True, False,  True, False, False])
```

The behavior is similar when using converters like so:
```python
>>> from rpy2.robjects import numpy2ri
>>> numpy2ri.rpy2py(bool_vec)
array([1, 0, 1, 0, 0], dtype=int32)
```

**Comment by lgautier** [comment] 2024-03-23 15:09
It is behaving as intended, although I understand that it can first seem counterintuitive.
This is because R includes the notion of missing values (NAs) down to all its array types.
For boolean arrays, values are encoded as integers at the C level.

Taking a slight modification of your example:
```python
>>> bool_vec = ro.BoolVector([True, False, True, None, False])
>>> print(bool_vec)
[1]  TRUE FALSE  TRUE    NA FALSE
```

Numpy will see the integers:

```python
>>> np.array(bool_vec)
array([          1,           0,           1, -2147483648,           0],
      dtype=int32)
```

The C-level numerical values for R's NAs are available as rpy2 constants
(see https://rpy2.github.io/doc/v3.5.x/html/vector.html#missing-values).

Note that `numpy`'s behavior is itself also counterintuitive. A `None` will
not trigger an error nor result in a missing value:

```python
>>> np.array([True, False, True], dtype='bool')
array([ True, False,  True])
>>> np.array([True, False, None], dtype='bool')
array([ True, False, False])
```

**Comment by lgautier** [comment] 2024-03-23 15:09
Closing as not a bug. Reopen if I missed anything.

**Closed by lgautier** 2024-03-23 15:09 UTC
Labels: bug
