### ISSUE TITLE
multithreading

### ISSUE THREAD

**Issue by JohnMulligan** [rpy2/rpy2#729] opened 2020-08-28 02:02 UTC
I'm using rpy2 3.3.5 with python 3.6.8 to run a Dash (1.15.0) Flask (1.1.2) app. 

The multithreading issue ( https://rpy2.github.io/doc/latest/html/changes.html ) doesn't appear to be resolved by using openrlib.rlock. I went so far as to only call openrlib in the main flask app and wrapped the import of the subprocess that uses robjects within openrlib.rlock. Still got a C stack usage limit error from Apache. I think that's descriptive enough but can append the code to this if that would be helpful.

(The code works fine in the standalone python script that calls R, of course.)

For context, I'm using this because the package I need (Farrington epidemiological surveillance) is only available in R. The alternative I think is to set up a standalone api for the flask app to call (e.g., Redis).

**Comment by lgautier** [comment] 2020-08-28 13:25
If you are able to share a minimal (code) example that triggers the problem, this would help figure out what is happening (either an incorrect use of `rlock` or an issue with its implementation).

Depending on your exact setup, it might be worth looking into having fully independent embedded R instances in child processes (the doc is trailing behind on that subject, but there is already a command line demo script illustrating how subprocesses are created has an influence on this - https://github.com/rpy2/rpy2/blob/master/doc/_static/demos/multiproc_lab.py).

**Comment by JohnMulligan** [comment] 2020-09-10 16:01
Hey I'm sorry for the delay here, I forgot which email account this is on. Perhaps I am using rlock improperly. Here's the flask app I'm running:


#!/bin/python3
import flask
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.express as px
import pandas as pd
from rpy2.rinterface_lib import openrlib
import datetime
import sys

##jursidiction is a state abbreviation string, e.g., 'YC' or 'NY' or 'DC' or 'TX'
try:
	jurisdiction=sys.argv[1]
except:
	jurisdiction='TX'

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']
server = flask.Flask(__name__)
app = dash.Dash(__name__, server=server, requests_pathname_prefix="/")
app.url_base_pathname = "/"
app.routes_pathname_prefix = app.url_base_pathname



def serial_date_to_string(srl_no):
    new_date = datetime.datetime(1970,1,1,0,0) + datetime.timedelta(srl_no - 1)
    return new_date.strftime("%Y-%m-%d")


with openrlib.rlock:
	import farrington
	d=farrington.main()
	pass

fig = px.bar(df, x="week_ending", y="observed", color='cause_group', barmode='group')

app.layout = html.Div(children=[
    html.H1(children='Hello Dash'),

    html.Div(children='''
        Dash via Python-Flask via RPY2
    '''),

    dcc.Graph(
        id='example-graph',
        figure=fig
    )
])

if __name__ == '__main__':
    app.run_server(debug=True)

**Comment by lgautier** [comment] 2020-09-13 04:00
A similar question was asked recently on StackOverflow:
https://stackoverflow.com/questions/63785478/multithreaded-flask-application-causes-stack-error-in-rpy2-r-process

As I answered there, I am now thinking that the issue might come from multiprocessing. Are you running Flask behind Gunicorn, or something else that might create child processes ?

**Comment by JohnMulligan** [comment] 2020-09-15 22:05
Yes, you've got it. Flask and wsgi. I wasn't smart enough to figure out how to configure the app to only create isolated child processes as you suggest there, but I think you're right that that would do it.

**Comment by lgautier** [comment] 2020-09-19 20:02
I am not an expert in Flask configuration. You might get an answer about how to control subprocess creation on a Flask mailing list, or StackOverflow.

**Comment by krassowski** [comment] 2021-01-09 18:47
Just a note: this started happening for me after upgrading to R 3.6 and rpy2 3.3.x from a prehistoric R 3.3 and rpy2 2.9.5. Previously all worked seamlessly. `rlock` does not solve the issue in any way. Most imports from rpy2 will cause a crash. Wrapping them with `rlock` does not help. Wrapping entire app init with `rlock` does not help.

**Comment by krassowski** [comment] 2021-01-09 18:49
Also it works locally when using the flask builtin server, its the apache + WSGI that causes the problem. Investigating further..

**Comment by krassowski** [comment] 2021-01-09 18:54
I wonder if this could help: https://github.com/JuliaInterop/RCall.jl/issues/289#issuecomment-452354863

**Comment by krassowski** [comment] 2021-01-09 19:51
Findings so far:

- crashes on `status = rlib.Rf_initEmbeddedR(n_options_c, options_c)`
- does not get to `rlib.R_CStackLimit = ffi.cast('uintptr_t', _c_stack_limit)`
- setting stack limit before does not help
- rlock does not help

I wonder what might have changed in R 3.x or rpy 3.0 that caused this change of behaviour (again, it worked perfectly before).

**Comment by krassowski** [comment] 2021-01-09 20:13
I think that this commit is the culprit: https://github.com/rpy2/rpy2/commit/752f1e8c10896545c35805e2b1b50b0b9afd1d2b (well the culprit is in the R code, but this workaround was very useful as it turns out). @lgautier would you consider reverting that commit and keeping the workaround?

**Comment by krassowski** [comment] 2021-01-09 20:18
Also, reverting to `rpy2==3.2.7` fixes the issue

**Comment by lgautier** [comment] 2021-01-09 21:15
> I wonder what might have changed in R 3.x or rpy 3.0 that caused this change of behaviour (again, it worked perfectly before).

rpy2-3.0 moved from a C-extension module to `cffi`. The sequence of calls to R's C API should be same (except few hidden bugs I found in the C-extension during the process). However, the C-extension was acquiring and keeping the GIL during initialization, which is not the case with `cffi`. The `rlock` was added to addressed that.

**Comment by lgautier** [comment] 2021-01-09 21:19
> The sequence of calls to R's C API should be same 

Well, the revision you are pointing out to indicates that this is not the case, and what I (re)moved broke it.

**Comment by lgautier** [comment] 2021-01-09 21:46
> @lgautier would you consider reverting that commit and keeping the workaround?
@krassowski, I am understanding that your PR #765 is a proposed fix. I am happy to create a bugfix release 3.4.2 after the PR is merged.

Speaking of which, is there a minimal example to reproduce (that could be added to the suite of automated tests)?

**Comment by krassowski** [comment] 2021-01-09 21:51
Yes, https://github.com/rpy2/rpy2/pull/765#issuecomment-757371373 ;) As hinted in that comment, it could end with "assert True" but I have no idea how to catch it when it does **not** work because it seems to kill the process and I could not catch any exception.

**Closed** 2021-01-09 23:27 UTC

**Comment by lgautier** [comment] 2021-01-10 16:59
The way the automated test was it isolates that test, and a segfault will just halt testing with an error. It is in release 3.4.2, now on pypi.
