### ISSUE TITLE
AttributeError: type object 'DataFrame' has no attribute 'from_items'

### ISSUE THREAD

**Issue by jolespin** [rpy2/rpy2#680] opened 2020-04-09 17:23 UTC
Need to change this to `.from_dict` for `pandas ≥ 1.0`
```
~/anaconda3/envs/soothsayer_env/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py in ri2py_dataframe(obj)
    189 def ri2py_dataframe(obj):
    190     items = tuple((k, ri2py(v)) for k, v in obj.items())
--> 191     res = PandasDataFrame.from_items(items)
    192     return res
    193 

AttributeError: type object 'DataFrame' has no attribute 'from_items'
```

**Comment by jolespin** [comment] 2020-04-09 17:32
I fixed it in my version:
```
@ri2py.register(DataFrame)
def ri2py_dataframe(obj):
    # items = tuple((k, ri2py(v)) for k, v in obj.items())
    # res = PandasDataFrame.from_items(items)
    items = OrderedDict((k, ri2py(v)) for k, v in obj.items())
    res = PandasDataFrame.from_dict(items)
    return res
```

**Comment by lgautier** [comment] 2020-04-10 01:31
Yes. This is one of the API-breaking changes in `pandas`. This is fixed in `master`, from which I hope to branch out the 3.3.x release series soon.

**Comment by jolespin** [comment] 2020-04-10 01:53
Is this `rpy2 v2.9.4` outdated? 
https://anaconda.org/r/rpy2

**Comment by lgautier** [comment] 2020-04-10 02:26
I'd say so. The current release series on pypi is 3.2.x.

Le jeu. 9 avr. 2020 à 21:54, Josh L. Espinoza <notifications@github.com> a
écrit :

**Comment by jolespin** [comment] 2020-04-10 18:34
Is it possible to update the version on `conda-forge` and `r` channels of anaconda as well?

**Comment by lgautier** [comment] 2020-04-10 22:52
This is a question that only the conda community can answer.

**Comment by lgautier** [comment] 2020-04-10 22:53
I'll close this because fixed `master`. rpy2-3.3.0 should be release soon.

**Closed by lgautier** 2020-04-10 22:53 UTC

**Comment by jolespin** [comment] 2020-04-11 00:30
Sounds good.  Do you know of a way I can let them know? It doesn’t seem that they have been up to speed with rpy2.

**Comment by lgautier** [comment] 2020-04-11 00:37
I don't know. I am not using conda myself. May be try on a mailing-list they might have, or on their project/product page.

**Comment by krassowski** [comment] 2020-04-11 16:16
@jolespin For conda-forge, https://github.com/conda-forge/rpy2-feedstock/ is an adequate repository to ask for help or contribute towards the aim of getting newer releases of rpy2. I would contact maintainers listed over there.

**Comment by GregSilverman** [comment] 2021-02-04 16:16
Hi,
I'm getting this error now using the latest version of rpy2 and pandas 1.1.3

```
/opt/anaconda3/envs/r/lib/python3.7/site-packages/rpy2/robjects/pandas2ri.py in ri2py_dataframe(obj)
    189         # current conversion as performed by numpy
    190
--> 191         res = func(obj)
    192         if len(obj.shape) == 1:
    193             if (obj.dtype != dt_O_type):

AttributeError: type object 'DataFrame' has no attribute 'from_items'
```

I looked at, and this is what is there:

```
251 @rpy2py.register(DataFrame)
252 def rpy2py_dataframe(obj):
253     items = OrderedDict((k, rpy2py(v) if isinstance(v, Sexp) else v)
254                         for k, v in obj.items())
255     res = PandasDataFrame.from_dict(items)
256     res.index = obj.rownames
257     return res
```

**Comment by jolespin** [comment] 2021-02-04 19:50
Can you show which version of rpy2 you are using?

**Comment by GregSilverman** [comment] 2021-02-04 19:54
rpy2   -> 3.4.2

**Comment by lgautier** [comment] 2021-02-06 00:13
@GregSilverman : Is the problem caught by the unit tests when your are running them with your version on pandas? If not, can you provide a minimal self-contained example to reproduce?

**Comment by DeDataDoctor** [comment] 2021-03-18 09:47
Unfortunately I have exactly the same problem. I think I have the same setup as Greg. I was not planning to downgrade pandas so I was looking for an alternative solution.
Here is my code that I used to test rpy2 in Jupyterlab.

`%reload_ext rpy2.ipython

import pandas as pd
import numpy as np
df = pd.DataFrame({
    'cups_of_coffee': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    'productivity': [2, 5, 6, 8, 9, 8, 0, 1, 0, -1]
})
df.transpose()

%%R -i df 
library(ggplot2)
ggplot(df, aes(x=reorder(cups_of_coffee,productivity), y=productivity)) + geom_col() + coord_flip()
`



It shows the following error after executing the last few lines.
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-3e652eec2936> in <module>
----> 1 get_ipython().run_cell_magic('R', '-i df', 'library(ggplot2)\nggplot(df, aes(x=reorder(cups_of_coffee,productivity), y=productivity)) + geom_col() + coord_flip()\n')

~\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2380             with self.builtin_trap:
   2381                 args = (magic_arg_s, cell)
-> 2382                 result = fn(*args, **kwargs)
   2383             return result
   2384 

<decorator-gen-122> in R(self, line, cell, local_ns)

~\Anaconda3\lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~\Anaconda3\lib\site-packages\rpy2\ipython\rmagic.py in R(self, line, cell, local_ns)
    688         """
    689 
--> 690         args = parse_argstring(self.R, line)
    691 
    692         # arguments 'code' in line are prepended to

~\Anaconda3\lib\site-packages\rpy2\robjects\functions.py in __call__(self, *args, **kwargs)
    176                           ' in the function\'s signature:\n- ')
    177             exception = ValueError
--> 178             _fix_map_symbols(symbol_mapping,
    179                              conflicts,
    180                              on_conflict,

~\Anaconda3\lib\site-packages\rpy2\robjects\functions.py in __call__(self, *args, **kwargs)
    105         fm = _formals_fixed(self)
    106         doc = list(['Python representation of an R function.',
--> 107                     'R arguments:', ''])
    108         if fm is rinterface.NULL:
    109             doc.append('<No information available>')

~\Anaconda3\lib\functools.py in wrapper(*args, **kw)
    838                             '1 positional argument')
    839 
--> 840         return dispatch(args[0].__class__)(*args, **kw)
    841 
    842     funcname = getattr(func, '__name__', 'singledispatch function')

~\Anaconda3\lib\site-packages\rpy2\ipython\rmagic.py in _(obj)
    147 
    148 
--> 149 # TODO: remove ?
    150 # # The R magic is opiniated about what the R vectors should become.
    151 # @converter.ri2ro.register(ri.SexpVector)

~\Anaconda3\lib\functools.py in wrapper(*args, **kw)
    838                             '1 positional argument')
    839 
--> 840         return dispatch(args[0].__class__)(*args, **kw)
    841 
    842     funcname = getattr(func, '__name__', 'singledispatch function')

~\Anaconda3\lib\site-packages\rpy2\robjects\pandas2ri.py in ri2py_listvector(obj)
    181                 raise ValueError('Series can only be of one type, or None '
    182                                  '(and here we have %s and %s).' %
--> 183                                  (homogeneous_type, type(x)))
    184         # TODO: Could this be merged with obj.type.name == 'O' case above ?
    185         res = _PANDASTYPE2RPY2[homogeneous_type](obj)

~\Anaconda3\lib\functools.py in wrapper(*args, **kw)
    838                             '1 positional argument')
    839 
--> 840         return dispatch(args[0].__class__)(*args, **kw)
    841 
    842     funcname = getattr(func, '__name__', 'singledispatch function')

~\Anaconda3\lib\site-packages\rpy2\robjects\pandas2ri.py in ri2py_dataframe(obj)
    189         # current conversion as performed by numpy
    190 
--> 191         res = func(obj)
    192         if len(obj.shape) == 1:
    193             if (obj.dtype != dt_O_type):

AttributeError: type object 'DataFrame' has no attribute 'from_items'
`

**Comment by suchzheng2** [comment] 2022-06-16 07:07
@DeDataDoctor Exactly same issue
