### ISSUE TITLE
NA_character_ not identified as NaN after importing it into Python

### ISSUE THREAD

**Issue by psads-git** [rpy2/rpy2#983] opened 2023-01-24 16:04 UTC
I am using the following code inside a R magic cell:

    %%R -o df
    
    library(tibble)
    
    df <- tibble(x = c("a", "b", NA))

However, when I run in another cell (a Python one):

    df.isna()

I get

           x
    1  False
    2  False
    3  False

In fact, the imported dataframe is 

                   x
    1              a
    2              b
    3  NA_character_

The following fixes the problem:

`df['x'] = df['x'].map(lambda val: np.nan if isinstance(val, rpy2.rinterface_lib.sexp.NACharacterType) else val)`

My question is: Should not this be done automatically by `rpy2`?

(For more details, please see: https://stackoverflow.com/questions/75223099/na-character-not-identidied-as-nan-after-importing-it-into-python-with-rpy2 )

**Comment by ievgennaida** [comment] 2023-01-27 10:23
Might be related:
https://github.com/rpy2/rpy2/issues/979

**Comment by lgautier** [comment] 2023-01-29 17:12
Thanks. This seems like a mistake in the conversion rules. The type of the column is `object`, and it leaves the special R value `NA_character_` as a Python object (and `pandas` does not consider it a missing value).

```python
In [8]: df.dtypes
Out[8]: 
x    object
dtype: object
```

**Comment by lgautier** [comment] 2023-02-05 22:59
With the PR #989 merged one now gets:

```python
In [5]: df
Out[5]: 
      x
1     a
2     b
3  None

In [6]: df.isna()
Out[6]: 
       x
1  False
2  False
3  True
```

**Closed by lgautier** 2023-02-05 22:59 UTC
Labels: bug

**Comment by D3SL** [comment] 2024-06-03 09:13
I'm having this bug with RPY 3.5.16. I was able to get around it briefly by using an older version of rpy2 (due to #1106) and converting through `pandas2ri.activate()`. In 3.5.16 there doesn't seem any way around this.

3.5.16 seems to be a severe regression in general when it comes to conversions. Previously I could run code like `foo=ro.r('''RCODE''')` or `ro.globalenv['bar']=pydata` without issue. Now I have to use the below undocumented pattern:
```
with (ro.default_converter + pandas2ri.converter).context():
   ro.r.assign('foo',ro.conversion.py2rpy(data) )
```

**Comment by lasagna0** [comment] 2024-12-12 21:57
You can handle R's NA values in a pandas DataFrame using rpy2's NACharacterType defined in the low level interface https://rpy2.github.io/doc/latest/html/rinterface.html . Here's how to properly convert R's NA values to Python's np.nan:

```

    import numpy as np
    from rpy2 import rinterface_lib
    
    # Convert R's NA to Python's np.nan
    dataframe = dataframe.applymap(lambda x: np.nan if isinstance(x, rinterface_lib.sexp.NACharacterType) else x) 
```

Also, the problem its persisting in the latest version of rpy2.
