### ISSUE TITLE
Kernel dies when loading large file to robjects

### ISSUE THREAD

**Issue by ngvananh2508** [rpy2/rpy2#1031] opened 2023-06-01 06:05 UTC
When I loaded a 4.5 Gb file to robject, the kernel of jupyter has died and the python kernel on terminal killed the process.
This is the code I use:
```python
import scanpy as sc
import anndata2ri
import logging
import numpy as np
import rpy2
 
import rpy2.rinterface_lib.callbacks as rcb
import rpy2.robjects as ro

sc.settings.verbosity = 0
sc.settings.set_figure_params(dpi = 80, facecolor = "white", frameon = False)

rcb.logger.setLevel(logging.ERROR)
ro.pandas2ri.activate()
anndata2ri.activate()

adata = sc.read(filename = "s1.h5ad")
ro.globalenv["adata"] = adata
```
I am using rpy2 version 3.5.12, python version 3.10.9, and my computer has 32 Gb Ram.

Can anyone instruct me how to assign more memory for rpy2 or python? I tried to find it on rpy2 or python docs but I cant find out it.

I am grateful for your help.

**Comment by lgautier** [comment] 2023-06-03 17:31
If this is a bug report, please open a bug report rather than an enhancement report. The template helps collect the information need to triage and help.

Also please indicate at which row the error occurs.

**Comment by ngvananh2508** [comment] 2023-06-04 01:56
When I ran this code: ro.globalenv["adata"] = adata, it appeared this issue. I realized this issue came from the overran of the memory. When I assigned 4.5 Gb data to this variable,  it temporally occupied more than 20 Gb RAM. I assumed this was not a bug so I opened the enhancement report. If you want me to change the title, please let me know.

**Comment by lgautier** [comment] 2023-06-04 17:31
> When I ran this code: ro.globalenv["adata"] = adata, it appeared this issue. I realized this issue came from the overran of the memory. When I assigned 4.5 Gb data to this variable, it temporally occupied more than 20 Gb RAM.

```python
ro.pandas2ri.activate()
anndata2ri.activate()

adata = sc.read(filename = "s1.h5ad")
ro.globalenv["adata"] = adata
```

The documentation is somewhat clear about using `pandas2ri.activate()` being deprecated (a warning should also be issued when you ran that code), and conversion being potentially expensive (see https://rpy2.github.io/doc/latest/html/robjects_convert.html#local-conversion-rules). Here you convert the result of `sc.read()` into a Python object (because of the added conversion rules) to immediately convert it back to R object with the code line that follows.  Leave the default converter and things should be *much* faster.

> I assumed this was not a bug so I opened the enhancement report. If you want me to change the title, please let me know.

A enhancement report describes what specific feature or behavior is wished from the package. Here this report reads like a note about running out RAM and asking for help. StackOverflow is a better place for questions.

**Comment by lgautier** [comment] 2023-06-04 17:31
Closing. Not a bug or an RFC or ask for enhancement. Reopen if not the case.

**Closed by lgautier** 2023-06-04 17:31 UTC
Labels: enhancement

**Comment by ngvananh2508** [comment] 2023-06-04 17:35
Thank you so much for your help.
